### ISSUE TITLE
Orphaned resources in projects cause constant change.

### ISSUE THREAD

**Issue by macdweller** [oboukili/terraform-provider-argocd#105]
If argocd_project.spec.orphaned_resources is not specified, terraform will happily create the object.  When you then immediately re-run a plan, it will want to make changes to the block:

```
  # argocd_project.<redacted> will be updated in-place
  ~ resource "argocd_project" "<redacted>" {
        id = "<redacted>"


      ~ spec {
            # (3 unchanged attributes hidden)



          - orphaned_resources {
            }
            # (2 unchanged blocks hidden)
        }
        # (1 unchanged block hidden)
    }
```

This is very annoying, as it will always result in changes occurring.  A lifecycle{ignore_changes} is necessary.  Specifying an empty block is not recommended due to issue #104; it will update just fine with the empty block, but recreating the resource will cause a crash.

**Comment by albgus** [comment]
I think creating the orphaned_resources is a bug in itself. I noticed that all projects created by this provider ends up with resource monitoring enabled, while the actual ArgoCD default would be disabled. Inspecting the yaml in kubernetes shows that the resources created by this module always has a `orphanedResources: {}` key in the spec, which enables resource monitoring and omitting this key leaves it disabled.
