### ISSUE TITLE
Enhancement: "metadata" block in "argocd_cluster" resource

### ISSUE THREAD

**Issue by jsfpdn** [oboukili/terraform-provider-argocd#111]
Hey @oboukili! Thanks for your work on this provider!

I have a question regarding the `argocd_cluster` resource - are you planning on adding support for the `metadata` block? Both `argocd_application` and `argocd_project` support it as of right now.

Our motivation for this is to create ArgoCD clusters via Terraform, label them, and use the label later on when defining ArgoCD Applications.

Thanks

**Comment by oboukili** [comment]
Should be a minor change and easy to add. I have had no time to work on the project lately, but it should be easy to submit a PR. The metadata schema is already factored in a specific function.

**Comment by jsfpdn** [comment]
@oboukili FYI, Argo CD has implemented gRPC support for cluster metadata in `v2.2.0-rc1`. We've implemented it and tested it in [our fork](https://github.com/wandera/terraform-provider-argocd/pull/1), but we had to mess around with the dependencies.

I suggest waiting for the stable release and then we'll create PR here.

**Comment by alxbse** [comment]
I also have my local fork where I have played around with the metadata support.

@oboukili What is the general approach here for adding functionality only available in upcoming argo-cd versions? Would you approve pull requests that require 2.2.0+ to master?

It would be really nice to have this support available in the provider as soon as the argo-cd is no longer a release candidate.

**Comment by riuvshyn** [comment]
hi guys, also interested in this. really looking forward to have an ability to define cluster labels.

**Comment by alxbse** [comment]
@jsfpdn Your branch is in the best state for a pull request since you actually updated the documentation and stuff. Would you like to open a pull request?
Once its merged I can help out testing it and improving on any outstanding issues.

**Comment by riuvshyn** [comment]
@alxbse I think @jsfpdn mentioned that it makes sense to wait for v2.2.0 goes to  stable.

**Comment by alxbse** [comment]
That is why I asked @oboukili if pull requests would be accepted before the stable release is out. I think it would be nice to get a head start here and collaborate on adding this support so that this provider can be released close to the release of argoo-cd 2.2.0 stable.

**Comment by riuvshyn** [comment]
@alxbse sure, I mean we can do this even in @jsfpdn fork, I am personally only interested in cluster registration aspect for now so might consider using forked version for now. But can also help with testing etc.

**Comment by jsfpdn** [comment]
@alxbse @riuvshyn created a pull request - #115. In the meantime, if you wish to use this without compiling it locally, [we've created a temporary repository in the Terraform registry with the fork](https://registry.terraform.io/providers/jojand/argocd/latest). We've been using it for a week or so and we've had no issues with it so far.
Let me know in the pull request if you wish to add/change/fix something.

**Comment by onematchfox** [comment]
Implemented in #140
