### ISSUE TITLE
New version of provider?

### ISSUE THREAD

**Issue by felipem1210** [oboukili/terraform-provider-argocd#116]
Hi, are there going to be more versions of this provider?
Punctually I'm looking to use a bug fix that is in master branch, but is not included in version 2.1.0.

Is this PR: https://github.com/oboukili/terraform-provider-argocd/pull/93

**Comment by oboukili** [comment]
Hi yes I am trying to fix the repository resource regression since argocd 2.1, but I m really struggling. I think if by the end of the week I can’t manage, I am just going to add a bug warning and release as is.

**Comment by crisp2u** [comment]
any updates on this ? we hit also the https://github.com/oboukili/terraform-provider-argocd/pull/93 bug. Can we help you with the regression ?
