### ISSUE TITLE
Honoring metadata finalizer when deleting Application.

### ISSUE THREAD

**Issue by mcanevet** [oboukili/terraform-provider-argocd#117]
Currently when an `argocd_application` resource is destroyed, cascade delete is performed, which is not the default behavior of the `Application` when you don't set the metadata finalizer (see https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#applications).
It would be great if we could define the finalizer in the `argocd_application` resource and that the provider honors it.

**Comment by raphink** [comment]
#121 aims to fix this

**Comment by oboukili** [comment]
closed by #121
