### ISSUE TITLE
regarding argocd server address using subpath method

### ISSUE THREAD

**Issue by manojkannekanti** [oboukili/terraform-provider-argocd#123]
when i try to use subpaths in argo cd server address, I am getting error.
server address - a.argocd.com/xyz (created using network load balancer and ingress ngnix, using open ports as 80, 443)
Error: dial tcp ; address tcp///a.argocd.com/xyz; unknown port

**Comment by onematchfox** [comment]
I'm going to close this issue as `Stale` given how old it is, and in the hope that you managed to resolve whatever was causing it. If this is still a problem, then please could I ask you to open a new issue with the full set of details on the provided template (as the current description does not give much to go on).
