### ISSUE TITLE
Adding a role project to an existing project causes crash in provider.

### ISSUE THREAD

**Issue by felipem1210** [oboukili/terraform-provider-argocd#125]
Hello,
I'm facing this problem, where I am trying to use the provider to modify an argocd_project where I want to add a role.

ArgoCD provider version: 2.1.0
ArgoCD version: 2.1.2
Terraform version: 1.0.9

http://linkode.org/#jtVHSDrErdveFIgL5YYmh5

This is not happening when I create the project with roles, just modifying

I'm passing the role this way:
`        {
          name     = "stg"
          policies = [
            "p, proj:staging:stg, applications, *, staging/*, allow"
          ]
        }`
   Not using description or groups due to they are not mandatory

**Comment by WitoldSlawko** [comment]
+1 same here @felipem1210 , 

@oboukili so looks the only way for now, is to destroy and re-create the project and apps again
