### ISSUE TITLE
Bit more documentation about intended use of the provider

### ISSUE THREAD

**Issue by immunochomik** [oboukili/terraform-provider-argocd#126]
Hello thank you for your great work!

It is not obvious from the Readme and examples, what is the intended use of this provider. I need something to bootstrap ArgoCD in a new cluster, from terraform (but doing it with plain k8s provider seems way too difficult). So I was looking at this repo, but it seems that it is not installing ArgoCD in a cluster but just configures existing ArgoCD installation so it can manage a preexisting cluster. It would save me few hours if the intended use of this would be clearly stated in Readme, one paragraph would do the job.

(I am still not sure if I am missing something and it really can install ArgoCD in my cluster or not)

Thank you

**Comment by oboukili** [comment]
Hi,

This provider indeed is meant to manage Argocd resources and is not about installing ArgoCD itself, like many providers out there (gitlab/elasticsearch/postgresql/mysql/mongodb/fluxcd/... etc). Documentation contributions are welcome of course, and I'll be more than glad to review a doc update should you want to take care of it.

Thanks,

**Comment by smshuja** [comment]
I too wasted a lot of my time assuming this would also install the cluster. I think this point should be the first one on the README file
