### ISSUE TITLE
Terraform apply continues updating without success

### ISSUE THREAD

**Issue by sarasensible** [oboukili/terraform-provider-argocd#135]
I am attempting to use this provider with an EKS cluster with port forwarding ( no load balancers as with other issue posters ).  I am unsure what the server address is supposed to be with the port forwarding enabled ( doc opportunity? ).  The Terraform apply continuously updates that it is creating without ever succeeding.

Terraform:
```
data "kubernetes_secret" "argocd_admin_password" {
  metadata {
    name = "argocd-initial-admin-secret"
    namespace = "tools"
  }
}

provider "argocd" {
  server_addr = "localhost:8443"
  username = "admin"
  password = lookup(data.kubernetes_secret.argocd_admin_password.data,"password","")
  insecure = true
  plain_text = true
  port_forward = true
  port_forward_with_namespace = "tools"

  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
}

resource "helm_release" "argocd" {
  name  = "argo-cd"
  repository = "https://argoproj.github.io/argo-helm"
  chart = "argo-cd"
  namespace = "tools"
  values  = [templatefile("${path.module}/helm/argocd-values.yaml", {})]
}

resource "argocd_application" "system" {
  depends_on = [helm_release.argocd]
  metadata {
    name      = "system"
    namespace = "tools"
  }

  spec {
    project = "default"
    source {
      repo_url        = "git@github.com:my-org/my-repo"
      chart           = "applications"
      target_revision = "main"
      path            = "system"
    }
    destination {
      server    = "https://kubernetes.default.svc"
      namespace = "tools"
    }
    sync_policy {
      automated = {
        prune     = false
        self_heal = true
      }
      # Only available from ArgoCD 1.5.0 onwards
      sync_options = ["Validate=false"]
    }
  }
}
```

Any help would be greatly appreciated.

**Comment by flaviomoringa** [comment]
Having the same issue, commented that on this ticket that I think is the same problem:
https://github.com/oboukili/terraform-provider-argocd/issues/120

**Comment by flaviomoringa** [comment]
I finally manage to fix it by adding the "  grpc_web = true " to the provider fields. Something like:
` 
provider "argocd" {
  # server_addr = "localhost:443"   # env ARGOCD_SERVER                                                                                                                                                                                             
  auth_token  = "xxxxxxx" # env ARGOCD_AUTH_TOKEN
  # username  = "admin"            # env ARGOCD_AUTH_USERNAME
  # password  = "foo"              # env ARGOCD_AUTH_PASSWORD
  insecure = false # env ARGOCD_INSECURE
  grpc_web = true
}
`

Hope it helps
