### ISSUE TITLE
Version 1.2.2 not available to arm64

### ISSUE THREAD

**Issue by haooliveira84** [oboukili/terraform-provider-argocd#139]
Hey folks!

I don't know happening, but the version v1.2.2 is not available to arm64, can you make it available again?
Another issue, I can't to use the versions above v1.2.2
See the error:
![Screen Shot 2022-02-21 at 17 00 33](https://user-images.githubusercontent.com/32314501/155019398-e7cfe657-93fe-4cc2-84b5-57bc2d7d482f.png)

**Comment by oboukili** [comment]
Hi, arm64 support is only supported from v2.0.0 onwards (https://github.com/oboukili/terraform-provider-argocd/releases/tag/v2.0.0), this was the first version to support Go 1.16. 
I don’t see why you would need to use such an old version though.

**Comment by oboukili** [comment]
The error you are describing means you are most likely using modules that force different  major version constraints. This is not related to this provider.
