### ISSUE TITLE
Cannot add a simple kubernetes cluster to argoCD

### ISSUE THREAD

**Issue by flaviomoringa** [oboukili/terraform-provider-argocd#158]
Hello,

when using the argo_cluster resource to add a simple k8s cluster to argo using this config:

```
resource "argocd_cluster" "kubernetes" {
  server = var.cluster_api_server
  name   = var.cluster_name

  config {
    bearer_token = var.cluster_bearer_token

    tls_client_config {
      ca_data = base64encode(var.cluster_ca_cert)
      insecure = false
    }
  }
}
```

I always get back the following error:

```
Error: something went wrong during cluster update: rpc error: code = Internal desc = Unable to apply K8s REST config defaults: unable to load root certificates: unable to parse bytes as PEM block
│ 
│   with argocd_cluster.kubernetes,
│   on argocd-simple_cluster.tf line 1, in resource "argocd_cluster" "kubernetes":
│    1: resource "argocd_cluster" "kubernetes" {
│ 
│ rpc error: code = Internal desc = Unable to apply K8s REST config defaults: unable to load root certificates: unable to parse bytes as PEM block
╵
```

I've tried multiple reconfigurations, even sending the base64 string directly on the "ca_data" variable and always the same error.  I've rechecked the string multiple times and it's the correct certificate.

In ArgoCD itself I can see the same log message

If I change the "insecure" to "true" it adds the cluster, but I don't want that.

If I create a manifest by hand, and do a "kubectl apply" of the manifest it  works ok.

What could be wrong here? why is the certificate not being well read?

I'm really stuck here, could someone help me?

Thanks in advance.
Flávio

**Comment by MrLuje** [comment]
What does `var.cluster_ca_cert` look like ?
If it is something like "LS0tLS1CRUdJTiBDRVJUSUZ...", I guess base64decode should be used :
```hcl
    tls_client_config {
      ca_data = base64decode(var.cluster_ca_cert)
      insecure = false
    }
```

**Comment by flaviomoringa** [comment]
Hi @MrLuje ,

but what value should the ca_data variable have? According with the example docs it should have the base64 encoded string, not the certificate value in plain text, right?

What you are saying is to decode  the base64 string, but isn’t that the opposite of what the docs say to do?

But maybe I’m seeing all of this wrong 😂

Can you explain better?

Thanks in advance.

**Comment by flaviomoringa** [comment]
@MrLuje,

you are totally right, just test it and it worked.

What threw me off was that on the documentation at [https://github.com/oboukili/terraform-provider-argocd/blob/master/docs/resources/cluster.md](https://github.com/oboukili/terraform-provider-argocd/blob/master/docs/resources/cluster.md) the first example states:

`ca_data = base64encode(file("path/to/ca.pem"))`

So I assumed it should be base64 encoded.

Thank you so much for your help.
