### ISSUE TITLE
Issue with application cascade delete

### ISSUE THREAD

**Issue by chap-dr** [oboukili/terraform-provider-argocd#171]
Greetings. 

I'm struggling with getting application deletes to cascade, when i disable or comment out a application module in my terraform code, the application is removed from ArgoCD but left lingering in the cluster it was installed in, As far as i can tell [this PR](https://github.com/oboukili/terraform-provider-argocd/pull/121/files) should address and do exactly what I seem to be missing here. 

Any pointers as to what I'm doing wrong here? or is this bug?

**Comment by MrLuje** [comment]
Cascade enabled & **foreground** delete policy should be the default behavior, except if specified otherwise.
What kind of source are you using ? (helm, etc)
Is there any events on k8s side to confirm if the deletion process is started but something preventing it ? (volume, loadbalancer, etc)

**Comment by chap-dr** [comment]
We're using Helm, and no, the install is left completely in place, The current one I'm testing with is kubed, We will be converting our Kuberentes bootstrap package into Terraform using the argocd provider so there will be more, So we've created an argocd-application module, that looks like this: 

```
resource "argocd_application" "application" {
  metadata {
    name      = var.argocd_name
    namespace = var.argocd_namespace
  }
  wait = var.wait
  spec {
    project = var.argocd_project
    source {
      repo_url        = var.repo_url
      chart           = var.chart
      target_revision = var.target_revision
      helm {
        dynamic "parameter" {
          for_each = local.merged_parameters
          content {
            name         = parameter.value.name
            value        = parameter.value.value
            force_string = parameter.value.force_string
          }
        }
        release_name = var.release_name
      }
    }

    sync_policy {
      automated = {
        prune       = var.sync_prune
        self_heal   = var.sync_self_heal
        allow_empty = var.sync_allow_empty
      }
      sync_options = var.sync_options
    }

    destination {
      server    = var.destination_server
      namespace = var.destination_namespace
    }
  }
}

variable "argocd_name" {
  description = "Display name of the application to be shown in the ArgoCD UI"
  type        = string
}

variable "argocd_namespace" {
  description = "Namespace of the ArgoCD instance that will manage this application"
  type        = string
}

variable "argocd_project" {
  description = "Name of the ArgoCD project to add this application to"
  type        = string
}

variable "wait" {
  description = "Wait for application to be synced and healthy upon creation and updates,"
  type        = bool
  default     = true
}

variable "repo_url" {
  description = "Helm Repository URL, (a repository must still be added to ArgoCD)"
  type        = string
}

variable "chart" {
  description = "Helm chart of the application"
  type        = string
}

variable "target_revision" {
  description = "Version of the Helm chart to be installed"
  type        = string
}

variable "parameters" {
  description = "A list of parameters to be passed to the Helm chart"
  type = list(object(
    {
      name         = string
      value        = string
      force_string = optional(bool)
    }
  ))
}

variable "release_name" {
  description = "Helm release name"
  type        = string
}

variable "sync_prune" {
  description = "Prune resources automatically as part of automated sync"
  type        = bool
  default     = false
}

variable "sync_self_heal" {
  description = "Enables auto-syncing if the live resources differ from the targeted revision manifests"
  type        = bool
  default     = false
}

variable "sync_allow_empty" {
  description = "Allows apps to have zero live resources"
  type        = bool
  default     = false
}

variable "sync_options" {
  description = "List of sync options, allow you to specify whole app sync-options"
  type        = list(string)
  default     = []
}

variable "destination_server" {
  description = "the server to install this app"
  type        = string
}

variable "destination_namespace" {
  description = "app namespace"
  type        = string
}
```

And yea, like i said, its just kubed, so no lb cleanup to hold things up or anything like that.. When I realized this was a problem the "lingering" kubed install was about more then 24 hours old.

**Comment by MrLuje** [comment]
Looks fine, you are even using `wait = true` so it should either properly deleted or apply should fail.
I wasn't able to reproduce with a kubed deploy.
No chance that the lingering resources don't come from this terraform plan ? Does it happen every time ? if yes, could you also try with ArgoCD CLI ?

**Comment by chap-dr** [comment]
No it does not appear to be related to lingering resources, We've tinkered around with it some more and found a "pattern" I guess. :) 

In our Terraform we register the cluster, create a project and then add apps to that project, all apps we install have a toggle so we can disable and enable install of certain apps. If we toggle this to off, the app is removed both in Argo and in cluster, If we do a full terraform destroy the cluster, project and app are all removed but apps are left in the cluster, so perhaps this is a timing issue between removal of cluster/project and app? 

our main tf looks like this (its longer then the example here but this should give a picture of how we are doing it) 
```
module "argocd_cluster_registration" {
  source                 = "./modules/argocd-cluster"
  name                   = local.name
  cluster_endpoint       = data.google_container_cluster.cluster.endpoint
  cluster_ca_certificate = data.google_container_cluster.cluster.master_auth.0.cluster_ca_certificate
}

module "argocd_project_creation" {
  source             = "./modules/argocd-project"
  argocd_name        = local.name
  argocd_namespace   = var.argocd_namespace
  destination_server = "https://${data.google_container_cluster.cluster.endpoint}"
}

module "kubed_helm" {
  count                 = var.kubed_enabled ? 1 : 0
  source                = "./modules/kubed"
  argocd_namespace      = var.argocd_namespace
  argocd_project        = module.argocd_project_creation.name
  cluster_endpoint      = data.google_container_cluster.cluster.endpoint
  public_cluster_domain = local.public_cluster_domain
  project_id            = local.project_id
  project_name          = local.project_name
}
```

**Comment by chap-dr** [comment]
@MrLuje Is this expected behaviour? if so, I'll close the issue.

**Comment by MrLuje** [comment]
I would say yes. As you stated, there is no explicit link between the cluster definition and its usage in the application (since using data.google_container_cluster to get the endpoint). Therefore if the cluster is deleted before the app, it can't send the order to delete the app to the cluster if it hasn't the link anymore.

About the explicit dependencies in `depends_on = [module.argocd_project_creation,module.argocd_cluster_registration]`, I may have to idea to improve it without the explicit dependency.
I suppose the `name` output of `module.argocd_project_creation` is declared as sending directly the `name` variable used as input.
If you use the `argocd_project.xxx.metadata[0].name` of the project created in `argocd_project_creation` as output, you are making an explicit dependency (and won't need the `depends_on`) and it shouldn't try to create/destroy the project before the application.

I have a doubt about the format of the cluster endpoint (`data.google_container_cluster.cluster.endpoint` vs `argocd_cluster.xxx.server`) but if it is the same value, the same trick could be applied to make it an explicit dependency.

**Comment by chap-dr** [comment]
Good points :) Thanks!

Thanks for looking into this and for the feedback..
