### ISSUE TITLE
Create application just hangs...

### ISSUE THREAD

**Issue by stobias123** [oboukili/terraform-provider-argocd#177]
Using the below manifest, just hangs on "still creating" forever. I confirmed I can create an application manually with the same settings.

TF Log debug output doesn't produce much. 

Any ideas?

```
resource "argocd_application" "helm" {
  metadata {
    name      = "api-foo-2"
    namespace = local.namespace
  }

  wait = false

  spec {
    project = "default"
    revision_history_limit = "30"
    source {
      repo_url        = "https://chartmuseum.foo"
      chart           =  "api-foo"
      target_revision = var.helm_version
      helm {
        parameter {
          name  = var.image_tag
          value = var.helm_version
        }
        values      = local.extra_yaml
        release_name = "api-foo"
      }
    }

    destination {
      server    = "cluster-url"
      namespace = local.namespace
    }
  }
}
```

**Comment by felipem1210** [comment]
There are several issues about the same, there you will find solutions:
https://github.com/oboukili/terraform-provider-argocd/issues/135
https://github.com/oboukili/terraform-provider-argocd/issues/120
https://github.com/oboukili/terraform-provider-argocd/issues/109

**Comment by onematchfox** [comment]
I'm going to close this issue as `Stale` given how old it is and in the hope that you managed to resolve whatever was causing it. Generally, though, these sorts of issues are related to how (and if) you have exposed the ArgoCD API server. In addition, a number of related changes have been made to ArgoCD and the provider itself that should alleviate this issue.

For reference, please check out the [latest provider documentation](https://registry.terraform.io/providers/oboukili/argocd/latest/docs) as this has been updated recently to try and give examples of how to connect to ArgoCD depending on how/if you have exposed the API server. If you are still having issues with the latest version, then please feel free to open a new issue, and we can take a fresh look.
