### ISSUE TITLE
Add support for adding a credential template

### ISSUE THREAD

**Issue by psimms-r7** [oboukili/terraform-provider-argocd#181]
You can also set up credentials to serve as templates for connecting repositories, without having to repeat credential configuration. For example, if you setup credential templates for the URL prefix https://github.com/argoproj, these credentials will be used for all repositories with this URL as prefix (e.g. https://github.com/argoproj/argocd-example-apps) that do not have their own credentials configured.

https://argo-cd.readthedocs.io/en/release-1.8/user-guide/private-repositories/#credential-templates

**Comment by MrLuje** [comment]
If I'm not mistaken, it is already implemented as `argocd_repository_credentials`
See https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/repository_credentials for an example

**Comment by onematchfox** [comment]
As per the comment above, this should already be possible. Let me know if that resource doesn't work for your use case for whatever reason.
