### ISSUE TITLE
Add support for using a github app for credential

### ISSUE THREAD

**Issue by psimms-r7** [oboukili/terraform-provider-argocd#182]
![image](https://user-images.githubusercontent.com/59482013/170477602-40706889-0add-41ca-b78d-820b6665bc7e.png)

**Comment by almereyda** [comment]
That would be nice, indeed.

**Comment by philamente** [comment]
As we need this as well I am giving it a try - the api interfaces etc are already there. So hopefully this serves as a good first attempt in golang.

Fork can be found here: [https://github.com/philamente/terraform-provider-argocd](url)

**Comment by almereyda** [comment]
This ^^ link is pointing to another location than it presents to the user. This one: https://github.com/philamente/terraform-provider-argocd, hopefully, doesn't.

**Comment by philamente** [comment]
@onematchfox  this issue/enhancement request can be closed btw ;)

What is your workflow for tagging a new release? Just asking as we might wait until we can pull it from terraform registry instead of having to use a local tf provider override.

**Comment by onematchfox** [comment]
> What is your workflow for tagging a new release? Just asking as we might wait until we can pull it from terraform registry instead of having to use a local tf provider override.

How quickly do you need the functionality? I've been delaying cutting a new release in the hope of getting #229 into it. However @oboukili has limited time to dedicate to this project so ultimately I'm not sure how long it will take to get that reviewed. Would it  work for you if I held off a couple more days and cut the release on Friday at the latest?

**Comment by philamente** [comment]
> 

Hey, Friday latest will work - no worries. Thanks! 👍

**Comment by onematchfox** [comment]
Added in #235. Will be released in https://github.com/oboukili/terraform-provider-argocd/releases/tag/v5.0.0
