### ISSUE TITLE
Provider use argocd cli login?

### ISSUE THREAD

**Issue by psimms-r7** [oboukili/terraform-provider-argocd#191]
Is it possible for the terraform provider to use the login details of the current user as logged in via the argocd cli?
So if I login to argocd cli as my account, then that same authentication can be used for the terraform provider?

**Comment by MrLuje** [comment]
Yes, with https://registry.terraform.io/providers/oboukili/argocd/latest/docs#use_local_config
```hcl
provider "argocd" {
  server_addr = "argocd.local:443"
  use_local_config = true
  context = "argocd.prod"    <--- optional, but useful if you have multiple contexts
}
```
