### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by Eric-Fontana-Indico** [oboukili/terraform-provider-argocd#193]
I updated to 3.1.0 of this module.  Now I am getting:

```
╷ 
╷ Error: Provider produced inconsistent final plan
╷
╷ When expanding the plan for module.argo-registration.argocd_project.eks to include new values learned so far during apply, provider "registry.terraform.io/oboukili/argocd" produced an invalid new value for .spec[0].destination: planned set element cty.ObjectVal(map[string]cty.Value{"name":cty.NullVal(cty.String), "namespace":cty.StringVal("argo"), "server":cty.StringVal("https://kubernetes.default.svc")}) does not correlate with any element in actual.
╷ 
╷ This is a bug in the provider, which should be reported in the provider's own issue tracker."
╷ 
```

**Comment by onematchfox** [comment]
Hi @Eric-Fontana-Indico,

Sorry for the slow response here. Is this still an issue with the latest version of the provider? If so, please could you provide the following information:

- What versions of both the provider and ArgoCD are you using?
- What does the plan look like prior to this error occurring?
- What does the configuration of the affected argocd_project resource look like?

**Comment by Eric-Fontana-Indico** [comment]
seems to be ok now

**Comment by onematchfox** [comment]
> seems to be ok now 

Great stuff. Thanks for confirming.
