### ISSUE TITLE
Issue with destroying the infrastructure

### ISSUE THREAD

**Issue by Aman1994** [oboukili/terraform-provider-argocd#196]
Hi, We install argocd using oboukili/argocd source and our code has something like 

```terraform
resource "helm_release" "argocd" {
  name             = "argo-cd"
  chart            = "argo-cd"
  repository       = "https://argoproj.github.io/argo-helm"
  create_namespace = true
  namespace        = "argocd"
  version          = "3.29.5"
  values           = [
    file("argocd.yaml")
  ]
  depends_on       = [
    sealedsecret_local.argocd_repos,
  ]
}

resource "kubectl_manifest" "argocd_secret" {
  yaml_body         = sealedsecret_local.argocd_repos.yaml_content
  force_new         = true
  server_side_apply = true
  wait              = true
}

resource "argocd_repository" "argocd_repos" {
  for_each        = var.argocd_repos
  ssh_private_key = file(each.value.ssh_private_key)
  repo            = each.value.url
  depends_on      = [
    helm_release.argocd
  ]
}
```
We deployed the infra using terraform and then went fine. Now, when we try to destroy we get

```
│ Error: Failed to init clients
│ 
│   with argocd_repository.argocd_repos["k8id"],
│   on argocd.tf line 49, in resource "argocd_repository" "argocd_repos":
│   49: resource "argocd_repository" "argocd_repos" {
│ 
│ EOF
╵
╷
│ Error: Failed to init clients
│ 
│   with argocd_repository.argocd_repos["k8id-config"],
│   on argocd.tf line 49, in resource "argocd_repository" "argocd_repos":
│   49: resource "argocd_repository" "argocd_repos" {
│ 
│ EOF

```
Any idea what the issue is ?

**Comment by Aman1994** [comment]
We managed to figure out and fix the issue. The fix was to add `plain_text  = true` in the argocd provider

**Comment by Fleuri** [comment]
I have a similar issue, but instead of EOF it states "Argo CD server address unspecified.

**Comment by onematchfox** [comment]
Hi @Aman1994, 

I am doing some cleanup on open issues on this repository. Did you manage to resolve this issue? From the outset, your initial premise is incorrect...

> We install argocd using oboukili/argocd source

Based on the Terraform code you have supplied you are actually installing ArgoCD using Helm as per

> resource "helm_release" "argocd" {

You have not provided the configuration you used for the ArgoCD provider itself, but the `EOF` error indicates that you have not configured the provider correctly based on how you have [exposed ArgoCD](https://argo-cd.readthedocs.io/en/stable/getting_started/#3-access-the-argo-cd-api-server). I would refer you to [the provider documentation](https://registry.terraform.io/providers/oboukili/argocd/latest/docs) on this matter. 

@Fleuri, your issue sounds like a similar problem. I.e. you have not configured the ArgoCD provider (at all in this case). Please see docs link above. 

Feel free to comment here if you are still having any issues and we can re-open this issue if required.

**Comment by onematchfox** [comment]
Just realised that I misread your issue... Your issue is on destruction (not apply). The error you are getting is quite feasible if the ArgoCD `helm_release` has been destroyed prior to the ArgoCD resources themselves since there would be no ArgoCD server to communicate with. Would that explain the issue?
