### ISSUE TITLE
Provider fails when port-forwarding with --insecure setting

### ISSUE THREAD

**Issue by karlschriek** [oboukili/terraform-provider-argocd#201]
I am running ArgoCD in `--insecure` mode and handling TLS termination within the service mesh. (This is meant as a central, multi-tenanted ArgoCD server that will server multiple other clusters, and the cluster will be available at argocd.mydomain.com). There are however some resources that we want to host on the same cluster as where ArgoCD is running, and we want the ArgoCD server to manage them as well. That includes rolling out Istio, setting up the service mesh and exposing the ArgoCD server to the outside world. So for this initial setup, I am using the following provider setup:

```terraform
provider "argocd" {
  server_addr                 = "argocd-server.svc.cluster.local:8888"
  port_forward                = true
  port_forward_with_namespace = "argocd"
  username                    = local.argocd_server_username
  password                    = local.argocd_server_password
  insecure                    = true
  kubernetes {
    host                   = module.my_cluster.kube_admin_config.0.host
    cluster_ca_certificate = base64decode(module.my_cluster.kube_admin_config.0.cluster_ca_certificate)
    token                  = yamldecode(module.my_cluster.kube_admin_config_raw).users[0].user.token
  }
}
```

This works if I start the ArgoCD server normally, but if I start it with the  `--insecure` flag, then I get `Error: Failed to init clients` when running terraform plan.

**Comment by SCHJOSEP** [comment]
I am confused at the syntax for the server_addr field. Is that an endpoint you set?

**Comment by onematchfox** [comment]
Hi @karlschriek, 

When running ArgoCD server with the `--insecure` flag, the ArgoCD server will be exposed over `http` and not `https`. As such, I believe you need to swap out `insecure = true` with `plain_text = true` on the provider config. 

If that doesn't work, could you confirm if this is still an issue on the latest version of the provider (and supported ArgoCD version) and if so, provide the full error message upon failure?
