### ISSUE TITLE
Remove validation ensuring cluster URL uniqueness

### ISSUE THREAD

**Issue by kayneb** [oboukili/terraform-provider-argocd#211]
If creating cluster manifests via kubectl, it is possible to have multiple instances of the same cluster, but there exists validation within this provider that a cluster being created does not have the same URL as another already present cluster. It is appealing to be able to duplicate URLs to enable the creation of multiple instances of the same cluster, scoped to different projects, in order to enable use of project role policies for constraining access.

FWIW, it seems like all necessary validation should occur on the server-side anyway, so implementing provider-side validation in general may easily get out of date with validation on the backend.

**Comment by onematchfox** [comment]
See related, #165, which introduced validation on cluster uniqueness

**Comment by kayneb** [comment]
Sorry my mistake, I meant to say cluster URL uniqueness! Updated.

**Comment by kayneb** [comment]
Definitely related to the mentioned PR.

**Comment by kayneb** [comment]
Upon letting my clusters with the same server URL sit for a while, I'm seeing some pretty odd behavior in the UI - viewing one of the duplicated clusters results in the cluster name cycling through all the different names I configured it with. It looks to be polling, and is looking the cluster up with the server URL. It's definitely assuming uniqueness. Closing.
