### ISSUE TITLE
Your code does not work mate, why are you forcing us to use ssh private keys ??? instead of tokens ??

### ISSUE THREAD

**Issue by rzvn2600** [oboukili/terraform-provider-argocd#213]
I added the ssh key and your code is throwing error. Also you did not add the TOKEN functionality that already works in ArgoCD!!
It's shameful to keep trying to make your code work mate, I spend some hours for absolutely nothing.

```
│ Error: Invalid block definition
│
│   on argocd.tf line 1:
│    1: ssh-rsa AAAA_a7UDGUY2WpS/4s+XcEwb4ZFZEUoNYmfjOeYrMN/adnrToqsW2oXDpYN9fx2ANxPPyItbF8wKcgJ4mn6gqIo8OyT1I6/jC3+Bu79mIl0jPl++2HxtNp8R177UD1WqG27haC8g7P+FUT0sZjSympO8tZuLWp1HAgJ9RpxvpqfG41kGqQeUNdv2Mc= root@586d916dac9f
│_REDACTED__
│ Either a quoted string block label or an opening brace ("{") is expected here.
```
Why didn't you add the token functionality here and you added the ssh loooong private key ???
Didn't you know that there are tokens as well mate ?

**Comment by rzvn2600** [comment]
Example from your documentation:
https://registry.terraform.io/providers/amitai-devops/argocd/latest/docs/resources/repository_credentials

**Comment by rzvn2600** [comment]
I was retarded. I was missing a last \n line

**Comment by oboukili** [comment]
First, thanks for those very respectful comments, truly motivating.

Second, it's a free open-source community project that we all maintain on our free time, it's (very much) open to contributions. Something you are missing? Feel free to open a PR.

Third, this provider is several years old, some new features that were not present during the inception of some resources simply are not integrated yet, such as the Github App credentials. 

Finally, the token use case is already supported with username/password, you have to read the documentation to set the correct username.
