### ISSUE TITLE
Correct location of value_files ?

### ISSUE THREAD

**Issue by VladoPortos** [oboukili/terraform-provider-argocd#219]
What is the correct location in Terraform for value_files ? 

There is nothing mentioned in the documentation just:

```
value_files = ["values-test.yml"]
```

So I would assume that the file is in root directory, same with all the Terraform files. However this does not seems to be true, since I'm getting: 

```
Error: open /tmp/c1e51a96-e9fc-44a5-b1e7-e4693a0e1275/zabbix-helm-chrt/zabbix.yaml: no such file or directory
```

No idea why its looking in some /tmp :-/

**Comment by oboukili** [comment]
Hi,
The values_files location is relative to the _Helm chart_'s base directory. These parameters are sent as they are to ArgoCD through the API, therefore the logic is done at the repo-server level.
AFAIK, the /tmp/ directory is used by the repo-server to clone Git repositories and Helm charts into. The repo-server is basically telling you it could not find your `zabbix.yml` values file within the Helm chart base directory.
Hope that helps!

**Comment by VladoPortos** [comment]
Thanks @oboukili  I was hoping that it would add it to values field in ArgoCD, cause the helm chart is usually remote location.

**Comment by VladoPortos** [comment]
Ou !! I know where my f@up is !

Looking at it now there is:
        value_files = ["values-test.yml"]  <---- This one just thell the ArgoCD to look for that file name in the same repo as helm chart
        values      = <<EOT <---- This one will add the yaml to values in ArgoCD

Now my question is, can I use `values` with external file ? Like: values = read_this_local_file('file.yaml') ?

**Comment by oboukili** [comment]
Hi, yes you can, as seen in the documented example https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/application :
```hcl
resource "argocd_application" "helm" {
  metadata {
    name      = "helm-app"
    namespace = "argocd"
    labels = {
      test = "true"
    }
  }

  wait = true

  spec {
    source {
      repo_url        = "https://some.chart.repo.io"
      chart           = "mychart"
      target_revision = "1.2.3"
      helm {
        parameter {
          name  = "image.tag"
          value = "1.2.3"
        }
        parameter {
          name  = "someotherparameter"
          value = "true"
        }
        value_files = ["values-test.yml"]
        values      = <<EOT
someparameter:
  enabled: true
  someArray:
  - foo
  - bar    
EOT
        release_name = "testing"
      }
    }

    destination {
      server    = "https://kubernetes.default.svc"
      namespace = "default"
    }
  }
}
```

You definitely might want to look at https://github.com/argoproj/argo-cd/issues/2789 that's landing in ArgoCD 2.6.

**Comment by VladoPortos** [comment]
That new feature looks great. 

I'm asking about this part:

```
        values      = <<EOT
someparameter:
  enabled: true
  someArray:
  - foo
  - bar    
EOT
```

Can I replace:
```
<<EOT
someparameter:
  enabled: true
  someArray:
  - foo
  - bar    
EOT
```

With `${file("somefile.yaml")}`

**Comment by oboukili** [comment]
Hi, you are free to try it for yourself, but I would guess that will work.
