### ISSUE TITLE
Revisit support for ApplicationSet

### ISSUE THREAD

**Issue by jcogilvie** [oboukili/terraform-provider-argocd#223]
I see that issue #88 was previously closed as infeasible, but it appears to be feasible now given the API support implemented for ApplicationSets:  https://github.com/argoproj/argo-cd/pull/9584

This would be a valuable addition to the provider.

**Comment by oboukili** [comment]
Agreed that is now feasible, and we are accepting contributions!
That being said, I still fail to see the added value ApplicationSets can bring if you are already using the Terraform provider. 
Indeed, one can already use `for_each` loops on the `argocd_application` resource. It's my understanding that ApplicationSets provide a workaround for the shortcomings of YAML, unless I am missing something?

**Comment by jcogilvie** [comment]
There is added value around allowing users to use plugins related to
application sets.

For instance, allowing argo to orchestrate promotions, like in this plugin
: https://github.com/Skyscanner/applicationset-progressive-sync)

Note that there is an approved enhancement proposal that looks to
incorporate it into argo proper:
https://github.com/argoproj/argo-cd/pull/9979

**Comment by oboukili** [comment]
Thanks I was not aware of that. This is a valid use case.

**Comment by aberenshtein** [comment]
+1 for applicationSet

**Comment by onematchfox** [comment]
FYI, I've done some initial work on implementing this [here](https://github.com/onematchfox/terraform-provider-argocd/tree/feat/application-set). However, this is a giant resource, and given other commitments coming up, I won't have the time to complete this work for quite a while. 

Outstanding work includes:
- Generators
  - [Merge](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Merge/)
  - [SCM Provider](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/)
  - [Cluster Decision Resource](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster-Decision-Resource/)
  - [Pull Request](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/)
- [Generator Templates](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/#generator-templates) 
- [`syncPolicy`](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#prevent-an-applications-child-resources-from-being-deleted-when-the-parent-application-is-deleted)
- [`strategy` (progressive sync)](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/)
- and, no doubt, something else I've missed. 

I'll continue chipping away at some of the outstanding work as time allows. But, if anyone wants to pick this up in and add to what I've done already, then please feel free to do so.
