### ISSUE TITLE
get application ressources on sync

### ISSUE THREAD

**Issue by Diliz** [oboukili/terraform-provider-argocd#234]
Hello!

I tried to create an argo application with this provider, but it seems that the argo application resource output is getting only the application ressource itself.

I was expecting to see the ressources deployed with the application, like when I do an argo app sync myapp or argo app get myapp.

Is it possible to add the ressources deployed with the application (since it's part of the argocd sync output), to make it available in my terraform plan at some point?

**Comment by onematchfox** [comment]
Hi @Diliz,

Firstly, sorry for the slow response. 

If `argocd sync` is returning this information then, yes, this should be possible using the provider. That said, I'm not sure I understand why you need this information (in the context of using Terraform to maintain applications) and/or how you would use this information if the provider output it. Would you perhaps be able to expand on this request to highlight why this is needed/what benefit adding it would provide?
