### ISSUE TITLE
5.0 breaking change fails to apply after the suggested change.

### ISSUE THREAD

**Issue by camalot** [oboukili/terraform-provider-argocd#236]
Using the latest 5.0 version of the provider, after making the `typeset` change to the config results in error of run.

example error:

```
Error: missing expected [
with module.argocd.argocd_application.application["centralus_abc"]
on ../modules/argocd/main.tf line 119, in resource "argocd_application" "application":
      automated {

Error: missing expected [
with module.argocd.argocd_application.application["centralus_def"]
on ../modules/argocd/main.tf line 119, in resource "argocd_application" "application":
      automated {
```

An additional error that is thrown:

```
Error: Failed to decode resource from state
Error decoding "module.argocd.argocd_application.application[\"centralus_def\"]" from previous state: missing expected [
```

_note: edit the errors to show that there are multiple environments configured (with the for_each), but only 1 of them returns the "additional error"._

Config 4.x
```
resource "argocd_application" "application" {
  for_each = var.environments
  spec {
  ...
    sync_policy {
      automated = {
        prune = true
        self_heal = true
        allow_empty = false
      }
      sync_options = [
        "PrunePropagationPolicy=foreground",
        "ApplyOutOfSyncOnly=true"
      ]
      retry {
        limit = 5
        backoff = {
          duration = "3m"
          factor = "2"
          max_duration = "30m"
        }
      }
    }
```

Config 5.0
```
resource "argocd_application" "application" {
  for_each = var.environments
  spec {
  ...
    sync_policy {
      automated {
        prune = true
        self_heal = true
        allow_empty = false
      }
      sync_options = [
        "PrunePropagationPolicy=foreground",
        "ApplyOutOfSyncOnly=true"
      ]
      retry {
        limit = 5
        backoff {
          duration = "3m"
          factor = "2"
          max_duration = "30m"
        }
      }
    }
```

**Comment by onematchfox** [comment]
Will see what I can do to try reproduce this. Am unfortunately away at the moment so might take me a few days to do so. In the meantime, if there's any additional context/logging around the error please do send it through.

**Comment by olympe-operator** [comment]
I had a similar issue. The way to fix this is either to remove from state and reimport:
```
terraform state rm 'module.argocd.argocd_application.application["centralus_abc"]'
terraform import 'module.argocd.argocd_application.application["centralus_abc"]'
```
or to directly fix the state by pulling it using `terraform state pull > /tmp/terraform-state`, then editing the sync_policy by adding the missing `[]` around `automated` and `backoff`:

before:
```
[...]
"sync_policy": [
    {
      "automated": {
        "allow_empty": false,
        "prune": false,
        "self_heal": true
      },
      "retry": [
        {
          "backoff": {
            "duration": "30s",
            "factor": "2",
            "max_duration": "2m"
          },
          "limit": "5"
        }
      ],
      "sync_options": []
    }
  ]
[...]
```
after:
```
[...]
"sync_policy": [
    {
      "automated": [
        {
          "allow_empty": false,
          "prune": false,
          "self_heal": true
        }
      ],
      "retry": [
        {
          "backoff": [
            {
              "duration": "30s",
              "factor": "2",
              "max_duration": "2m"
            }
          ],
          "limit": "5"
        }
      ],
      "sync_options": []
    }
  ]
[...]
```
then saving the file and execute `terraform state push /tmp/terraform-state`

**Comment by philamente** [comment]
> Will see what I can do to try reproduce this. Its unfortunately going to take me a few days to do so due to other commitments. In the meantime, if there's any additional context/logging around the error please do send it through.

I think this breaks it right now as this got converted to a list. But the terraform state when running the tf apply/ tf provider upgrade does not flatten to a list.

https://github.com/oboukili/terraform-provider-argocd/blob/a63eecbabc636c798c2a2b27f79771cf9c856753/argocd/structure_application.go#L450

**Comment by oboukili** [comment]
I did not have the chance to look at the code yet, but it sounds like there is an issue with the State version migration function.

**Comment by onematchfox** [comment]
> I did not have the chance to look at the code yet, but it sounds like there is an issue with the State version migration function.

Yeah, definitely an issue with the state migration function. And I think I've found the problem (and solution). PR incoming.
