### ISSUE TITLE
"automated" on the "argocd_application" resource is an argument, not a block

### ISSUE THREAD

**Issue by Aransh** [oboukili/terraform-provider-argocd#237]
According to documentation (on both the hashicorp registry, and the examples shown here), this is the correct syntax to define a sync policy on an argocd_application:

```
    sync_policy {
      automated {
        prune       = true
        self_heal   = true
        allow_empty = true
      }
    }
```

But, using this syntax I get this error:
`Blocks of type "automated" are not expected here. Did you mean to define argument "automated"? If so, use the equals sign to assign it a value.`

Adding an equal sign like this works:
```
    sync_policy {
      automated = {
        prune       = true
        self_heal   = true
        allow_empty = true
      }
    }
```

Not sure if this is something to fix, or just to update the documentation, either way could help others

**Comment by onematchfox** [comment]
@Aransh what version of the provider are you using? This syntax (should have) changed in 5.0 and the docs were updated accordingly.

**Comment by Aransh** [comment]
@onematchfox You are correct, did not notice another team member locked us to version 4.3.0
Updated now and all is working as expected, closing this.
Thanks :)
