### ISSUE TITLE
Unable to create applications when targetting ArgoCD v2.6.7

### ISSUE THREAD

**Issue by SietseT** [oboukili/terraform-provider-argocd#247]
There seems to be a [breaking](https://github.com/argoproj/argo-cd/issues/13000) change in how Applications are handled in v.2.6.7 of ArgoCD, which causes issues with the provider. I've tested this with 4.x.x versions and also the latest version 5.0.1.

When creating an application, I'm always getting the following error:
```
Error: application feedback could not be created
rpc error: code = PermissionDenied desc = permission denied
```

Previously, I used an older version of ArgoCD and it worked fine there.

**Comment by onematchfox** [comment]
Thanks for reporting. We are aware of the issue and this will be fixed in #240 (currently waiting on review)
