### ISSUE TITLE
Problem with helm parameters from type list

### ISSUE THREAD

**Issue by evtimokn** [oboukili/terraform-provider-argocd#253]
I am using the provider version 5.1.0 and I am trying to install a helm chart with ingress support, for which I have to define some parameters similar to the documentation:

      helm {
        parameter {
          name  = "installCRDs"
          value = "true"
        }
        parameter {
          name = "server.ingress.enabled"
          value = "true"
        }
        parameter {
          name = "server.ingress.ingressClassName"
          value = "some-nginx"
        }
        parameter {
          name = "server.ingress.hosts"
          value = "argocd.${var.hostname}"
        }

Whenever I have a parameter, which is declared as list in the values.yaml of the helm-chart, I am getting a 502 error.

module.argo.argocd_application.argocd: Creating...
╷
│ Error: application argocrd-tempstaging could not be created
│
│   with module.argo.argocd_application.argocd,
│   on modules/argo/main.tf line 72, in resource "argocd_application" "argocd":
│   72: resource "argocd_application" "argocd" {
│
│ rpc error: code = Unknown desc = POST
│ https://argocd.someserver:443/application.ApplicationService/Create
│ failed with status code 502

Seems either my syntax is wrong or the paramter-field is not working for lists.

**Comment by onematchfox** [comment]
Hi @evtimokn,

This is a bit odd since the `502` error code ("Bad Gateway") indicates an issue on ArgoCD server (or potentially some other proxy/LB involved in the request). Have you checked the ArgoCD server logs to see if these give any indication of why the error occurs?

> Whenever I have a parameter, which is declared as list in the values.yaml of the helm-chart, I am getting a 502 error.

How are you setting the `value` of the `parameter` block in the Terraform code?

**Comment by onematchfox** [comment]
OK, my guess is the problem is due to you setting the value to a simple string.

>   value = "argocd.${var.hostname}"

Check the [Helm docs](https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set) for more info on what you should be passing. Perhaps the following works?

> Lists can be expressed by enclosing values in { and }. For example, --set name={a, b, c} translates to:
> 
> ``` yaml
> name:
>   - a
>   - b
>   - c
> ```

**Comment by evtimokn** [comment]
Your guess is also my guess, I know how it looks like in yaml etc., but the point here is it needs to be translated somehow in the terraform code, which is the block above. The documentation of the provider says nothing about this, only about the simple string values. I am not that good in reading the golang code of the provider, so I can hardly figure out how the correct syntax looks like.

**Comment by onematchfox** [comment]
Have you tried "enclosing [the] value[s] in { and }" as the docs state?

E.g. 

```tf
parameter {
  name = "server.ingress.hosts"
  value = "{argocd.${var.hostname}}"
}

```

**Comment by evtimokn** [comment]
This worked finally:

parameter {          
          name = "server.ingress.hosts[0]"
          value = "argocd.${var.hostname}"
}
