### ISSUE TITLE
Trying to whitelist the "Namespace" resource results in "group '' is empty"

### ISSUE THREAD

**Issue by Chilinot** [oboukili/terraform-provider-argocd#257]
If you try to whitelist the `Namespace` resource using the following:

```hcl
resource "argocd_project" "project" {
 ...
 cluster_resource_whitelist {
  group = ""
  kind = "Namespace"
 }
 ...
}
```

Results in the following error: `group '' is empty`.

As far as i understand, this is a perfectly legal thing to do, and is how you would whitelist the namespace resource for the core group.

**Comment by onematchfox** [comment]
@Chilinot, as you will see, I have opened up a PR to allow a blank `Group` to be specified. In the meantime, `Group` is actually optional, so you could just leave this out. E.g.

``` tf
resource "argocd_project" "project" {
 ...
 cluster_resource_whitelist {
  kind = "Namespace"
 }
 ...
}
```

**Comment by Chilinot** [comment]
Alright thanks!
