### ISSUE TITLE
Add support for `pass_credentials` in helm

### ISSUE THREAD

**Issue by jcogilvie** [oboukili/terraform-provider-argocd#269]
### Description

Helm sometimes requires the `pass_credentials` flag to be set on the `argocd_application`.  The provider should support this.

### Potential Terraform Configuration

```hcl
  spec {
    destination {
      server = "https://kubernetes.default.svc"
    }

    source {
      helm {
        release_name = local.service_name
        values       = local.helm_values
        pass_credentials = true
      }
    }
  }
```

### References

https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-pass-credentials

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by duncan485** [comment]
I'm a bit new to terraform provider (at least writing them), but I'd like to give this one a try.

**Comment by duncan485** [comment]
Hey @onematchfox I've created  #271 . Can you link it to this issue? I wasn't sure whether I should introduce a new schema version for this change. But I've tested the provider locally and it is functional like this.
