### ISSUE TITLE
Perpetual diff on `argocd_repository`

### ISSUE THREAD

**Issue by jcogilvie** [oboukili/terraform-provider-argocd#270]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version

```
Terraform version: 1.4.6
ArgoCD provider version:  ~5.2.0
ArgoCD version: 2.6.7
```

### Affected Resource(s)
- `argocd_repository`

### Terraform Configuration Files
```hcl
resource "argocd_repository" "this" {
  repo = data.github_repository.this.http_clone_url
}
```

### Plan Output
```
  # module.this_app.argocd_repository.this will be updated in-place
!   resource "argocd_repository" "this" {
-       githubapp_id              = "123456" -> null
-       githubapp_installation_id = "123456789" -> null
        id                        = "https://github.com/myorg/myrepo.git"
        # (6 unchanged attributes hidden)
    }
```

### Steps to Reproduce
1. Create a credential template which configures github app auth
2. Create an `argocd_repository` that uses said credential template (i.e. leaves auth blank)
3. Observe that on continued `apply` calls, the `repository` fields for `githubapp*` create a perpetual diff, attempting to be nulled out 

### Expected Behavior
These fields should be ignored if the repo is using a credential template

### Actual Behavior
A diff every time I plan

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by onematchfox** [comment]
Hi @jcogilvie,

I'm afraid this behaviour is outside the control of the provider. If ArgoCD is updating the underlying `Secret`, then there is nothing we can do about that. Terraform is correctly detecting drift on this object in that the object's live state is different from what is defined in the Terraform code. To avoid this, you will need to define the auth on the repository to avoid the diff. Alternatively, it might be worth thinking about why you are even defining the repository in the first place. When using [repository credentials](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials) (e.g. GitHub App repositories), there is no need to define each repository individually; ArgoCD will automatically use the GitHub App for authentication on any repository within the defined org.

**Comment by jcogilvie** [comment]
So, there's nothing you can do here to ignore changes given the fact that you know the credentials are inherited?

```
[inherited_creds](https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/repository#inherited_creds) (Boolean) Whether credentials were inherited from a credential set.
```

**Comment by onematchfox** [comment]
FYI: when digging into this, I found a bug in the ArgoCD API whereby the value of `inherited_creds` was not propagated via API endpoints (it will always be `false`). This will hopefully be addressed in https://github.com/argoproj/argo-cd/pull/13428, so once that is merged, we can re-consider this issue.
