### ISSUE TITLE
support for `ignoreMissingValueFiles` helm application parameter

### ISSUE THREAD

**Issue by matiza5** [oboukili/terraform-provider-argocd#287]
### Description
Hi,

I have seen recent PR which adds support for `ref` keyword for multi sourced applications and external value files. This is great - I was waiting for it for a long time.
There is one more small thing missing: `ignoreMissingValueFiles` parameter, which I'm using a lot. The default is false, so every listed file in `valueFiles` must be present. I'm doing some kind of bootstrap of kubernetes clusters with ArgoCD, each cluster uses `common.yaml` values file and optionally `%cluster_name%.yaml` value file if there is any override to default, common values.

Is it possible to add support for this parameter... ? WDYT?
Unfortunately I won't be able to code it by myself, cause my golang skills are pretty poor.

Thanks for all your great work! Appreciate it!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by onematchfox** [comment]
Closed by #292. Will be part of next release.
