### ISSUE TITLE
When defining args for cluster it always wants to recreate

### ISSUE THREAD

**Issue by tesharp** [oboukili/terraform-provider-argocd#297]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version

```
Terraform version: 1.4.6
ArgoCD provider version: 5.3
ArgoCD version: 2.7.1
```

### Affected Resource(s)

- argocd_cluster

### Terraform Configuration Files
```hcl
...
command: "kubelogin",
args: [
            "get-token",
            "--login",
            "workloadidentity",
            "--server-id",
            "6dae42f8-4368-4678-94ff-3960e28e3630",
          ]
```

### Steps to Reproduce

Every time running `terraform apply` it will suggest a change to args. Can verify that the secret in kubernetes has the correct value, it just seems like provider does not register that it is the same

### Expected Behavior

No change on apply

### Actual Behavior

```
      ~ config {
          ~ exec_provider_config {
              ~ args        = [
                  + "get-token",
                  + "--login",
                  + "workloadidentity",
                  + "--server-id",
                  + "6dae42f8-4368-4678-94ff-3960e28e3630",
                ]
                # (3 unchanged attributes hidden)
            }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by onematchfox** [comment]
Unfortunately it looks like the ArgoCD API treats both `args`  and `env` as [potentially sensitive data](https://github.com/argoproj/argo-cd/blob/8840929187f4dd7b9d9fd908ea5085a006895507/server/cluster/cluster.go#L448-L466). This means that, yes, this is definitely a bug in the provider and, that we are unable to track remote state for these attributes.
