### ISSUE TITLE
Authenticate on unexposed API using port-forward

### ISSUE THREAD

**Issue by d3ployment** [oboukili/terraform-provider-argocd#300]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version

```
Terraform version: 1.4.5
ArgoCD provider version: 5.5.0
ArgoCD version: 2.7.4
```

## Question

I have a repo where I use three providers : scaleway/scaleway (to provision my kubernetes cluster), gavinbunney/kubectl (to install argocd) and oboukili/argocd (to manage Argo CRDs)

I'm trying to reach the Argo API with port-forward but it doesn't seem to work with my current configuration :

```hcl
... # Cluster provisioning with scaleway/scaleway

resource "null_resource" "kubeconfig" {
  depends_on = [
    scaleway_k8s_pool.default
  ]
  triggers = {
    host                   = scaleway_k8s_cluster.devops.kubeconfig[0].host
    token                  = scaleway_k8s_cluster.devops.kubeconfig[0].token
    cluster_ca_certificate = scaleway_k8s_cluster.devops.kubeconfig[0].cluster_ca_certificate
  }
}

... # Argo CD installation with gavinbunney/kubectl

provider "argocd" {
  port_forward = true
  auth_token   = null_resource.kubeconfig.triggers.token
}

resource "argocd_repository" "infra-components" {
  depends_on = [
    kubectl_manifest.argocd
  ]
  repo = "https://MY_URL"
}
```

Fail during apply with the following error :

```
Terraform has been successfully initialized!
argocd_repository.infra-components: Creating...


│ Error: failed to init clients
│ 
│   with argocd_repository.infra-components,
│   on main.tf line 90, in resource "argocd_repository" "infra-components":
│   90: resource "argocd_repository" "infra-components" {
│ 
│ invalid configuration: no configuration has been provided, try setting
│ KUBERNETES_MASTER environment variable
```

Can anyone help me figure out what is wrong with my configuration ?
Thanks in advance

**Comment by onematchfox** [comment]
Hi @d3ployment,

The error you are receiving is indicative of a problem with your Kube config file. Possibly it cannot be found - try setting the `KUBE_CONFIG_PATH` environment variable)? Or alternatively, it might be configured to use the wrong context - the configuration options under the [`kubernetes` block](https://registry.terraform.io/providers/oboukili/argocd/latest/docs#nested-schema-for-kubernetes) on the provider may help here?

Also, whilst you are not there yet... FYI, I strongly suspect that the `auth_token` you are providing to the `argocd` provider is also incorrect. From the look of it, you are currently passing in a token used to authenticate with the Kubernetes API whereas the `auth_token` on the provider should be an **ArgoCD** authentication token.
