### ISSUE TITLE
Create state migrator for ksonnet drop

### ISSUE THREAD

**Issue by stephan242** [oboukili/terraform-provider-argocd#304]
Could this still be done? I'm currently upgrading, and doing this manually in all the state files we've got seems quite dangerous ...

              Good point, we should have shipped a state migrator with the latest major release!

_Originally posted by @oboukili in https://github.com/oboukili/terraform-provider-argocd/issues/207#issuecomment-1297022746_

**Comment by onematchfox** [comment]
Hi @stephan242,

That version did actually ship with a state migration function so it should all go smoothly.

1. what error are you getting?
2. what versions are you upgrading from and to?
3. are you/have you been making use of ksonnet?
