### ISSUE TITLE
Error: Failed to init clients

### ISSUE THREAD

**Issue by NahumLitvin** [oboukili/terraform-provider-argocd#308]
Hi guys I really tried to connect using port forward, spent a whole day and keep getting this error

using the same k8s block as for connecting to the cluster
password is correct
the argocd server is insecure.

Error: Failed to init clients

```hcl
provider "argocd" {
  port_forward_with_namespace = "argocd"
  username                    = "admin"
  password    = aws_secretsmanager_secret_version.argocd.secret_string
  plain_text = true
  kubernetes {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "--profile", var.aws_profile, "get-token", "--cluster-name", module.eks.cluster_name]
  }
}
}

# Public Git repository
resource "argocd_repository" "public_git" {
  repo = "https://github.com/oboukili/terraform-provider-argocd.git"
} 
```

apply keeps failing on Error: failed to init clients

  with ******,
  on ***, in resource "argocd_repository" "public_git":
  **: resource "argocd_repository" "public_git" {

error loading config file "/configs": read /configs: is a directory

any advice?
I tried all combos. I found in previous issues.

**Comment by onematchfox** [comment]
Hi @NahumLitvin,

I haven't come across this before myself. However, two things spring to mind...

1. The error message is indicative of an issue in accessing your kubeconfig. Do you have an environment variable `KUBECONFIG` set, and if so, what is this set to? Might be worth playing around with this? 
2. I have no idea how port forwarding works when the ArgoCD server is running in insecure mode. Have you confirmed you can do this (or at least what configuration works) using the ArgoCD CLI (e.g. `argocd login ...`)?

Also, can you please confirm which versions of the provider, ArgoCD, Terraform, and, in this case, Kubernetes you are using?

**Comment by NahumLitvin** [comment]
tf 1.5
argo v2.6.7+5bcd846
k8s 1.27

not sure what the `KUBECONFIG` is and have no way to find out as it runs in a server beyond my control.

I have defined "kubernetes" provider.
shouldn't it be used instead of `KUBECONFIG`

**Comment by onematchfox** [comment]
> I have defined "kubernetes" provider.
> shouldn't it be used instead of KUBECONFIG

Unfortunately not. The `KUBECONFIG` environment variable is an override AFAIK. The provider actually doesn't have any code related to this environment variable, rather, this is the standard behaviour of the underlying k8s go module.

Can you run the Terraform code locally to confirm what settings work?

**Comment by Sudhanshu-Saurav** [comment]
@NahumLitvin I am also facing the same issue
![code-server](https://github.com/argoproj-labs/terraform-provider-argocd/assets/91416962/e1ca3c3f-9c03-48f2-b0aa-3eea848757bc)

**Comment by umar-rayn** [comment]
could you please show mw your provider file I m getting error 
 Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/argocd: provider registry registry.terraform.io does not
│ have a provider named registry.terraform.io/hashicorp/argocd
│ 
│ Did you intend to use claranet/argocd? If so, you must specify that source address in each module which requires that provider. To
│ see which modules are currently depending on hashicorp/argocd, run the following command:
│     terraform providers

terraform providers | grep argocd
├── provider[registry.terraform.io/oboukili/argocd] 6.2.0
    └── provider[registry.terraform.io/hashicorp/argocd]

terraform {
  required_providers {
    argocd = {
     source = "oboukili/argocd"
     version = "6.2.0"
   }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.38.0"
    }
  }
}

provider "argocd" {
  use_local_config = true 
}
