### ISSUE TITLE
Kustomize patch

### ISSUE THREAD

**Issue by henioStraszny** [oboukili/terraform-provider-argocd#310]
### Description

In argocd_application (Resource) add ability to use Kustomize patch transformer

https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_patchtransformer_

**Comment by onematchfox** [comment]
Hi @henioStraszny,

To be honest, I'm a little confused by this request. The functionality you link to is standard Kustomize behaviour. What do you feel needs to be changed in the provider to add the ability to use this? Is there specific configuration within ArgoCD that enables use of this and can you link to the ArgoCD documentation around this?

**Comment by dorsegal** [comment]
Argocd allow to define patches in application CRD
https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#patches

According to latest version I don't see `patches` as one of the attributes
https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/application#nestedblock--spec--source--kustomize

It will be much helpful to implement this

**Comment by onematchfox** [comment]
@dorsegal thanks for the additional info. That makes more sense now. Please feel free to create a Feature Request issue for this if it's something you'd like. This ticket hasn't provided any context, nor has the author provided any feedback. So I won't reopen it as it would mean extra work for myself and I don't have time for that.

**Comment by dorsegal** [comment]
> @dorsegal thanks for the additional info. That makes more sense now. Please feel free to create a Feature Request issue for this if it's something you'd like. This ticket hasn't provided any context, nor has the author provided any feedback. So I won't reopen it as it would mean extra work for myself and I don't have time for that.

Thank you! appreciate your time and work. I just opened a new one.
