### ISSUE TITLE
problem to join eks cluster to argocd cluster

### ISSUE THREAD

**Issue by nautiker** [oboukili/terraform-provider-argocd#311]
Adding argocd_cluster fails with 5.5

```
Terraform Version, ArgoCD Provider Version and ArgoCD Version
Terraform version: 1.5.0
ArgoCD provider version: 5.5
ArgoCD version: v2.2.5+8f981cc
eks cluster 1.24
```

### Affected Resource(s)
- argocd_cluster

###Terraform Configuration
```
resource "argocd_cluster" "eks" {
  server     = data.aws_eks_cluster.eks_private_cluster.endpoint
  name       = aws_eks_cluster.eks_private_cluster.name
  namespaces = ["kube-system"]

  config {
    aws_auth_config {
      cluster_name    = aws_eks_cluster.eks_private_cluster.name
      role_arn     = var.role-eks-cluster-control-plane
    }
    tls_client_config {
      ca_data = data.aws_eks_cluster.eks_private_cluster.certificate_authority[0].data
    }
  }
}
```

### Debug Output

argocd_cluster.eks: Creating...
40╷
41│ Error: failed to create cluster https://0a3dedf5f0f28b6783c535b357bc6956.gr7.us-east-1.eks.amazonaws.com/
42│ 
43│   with argocd_cluster.eks,
44│   on argocd.tf line 14, in resource "argocd_cluster" "eks":
45│   14: resource "argocd_cluster" "eks" {
46│ 
47│ rpc error: code = Internal desc = Unable to apply K8s REST config defaults:
48│ unable to load root certificates: unable to parse bytes as PEM block

### Actual Behavior
Crashing on apply

### Community Note
Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by onematchfox** [comment]
Hi @nautiker,


I think this may just be a mistake in our documentation. Can you try base64 decoding the CA data? E.g.:

```tf
resource "argocd_cluster" "eks" {
  server     = data.aws_eks_cluster.eks_private_cluster.endpoint
  name       = aws_eks_cluster.eks_private_cluster.name
  namespaces = ["kube-system"]

  config {
    aws_auth_config {
      cluster_name    = aws_eks_cluster.eks_private_cluster.name
      role_arn     = var.role-eks-cluster-control-plane
    }
    tls_client_config {
      ca_data = base64decode(data.aws_eks_cluster.eks_private_cluster.certificate_authority[0].data)
    }
  }
}
```

**Comment by nautiker** [comment]
thanks @onematchfox, the error "unable to load root certificates: unable to parse bytes as PEM block", was resolved but now i have other error:

Error: failed to create cluster https://xxxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com/
61│ 
62│   with argocd_cluster.eks,
63│   on argocd.tf line 14, in resource "argocd_cluster" "eks":
64│   14: resource "argocd_cluster" "eks" {
65│ 
66│ rpc error: code = Unknown desc = Get
67│ "https://xxxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com/version?timeout=32s":
68│ getting credentials: exec: executable aws failed with exit code 255
