### ISSUE TITLE
ArgoCD cluster not refreshing state after manually destroy it

### ISSUE THREAD

**Issue by paco-sisutech** [oboukili/terraform-provider-argocd#319]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version
```
Terraform version: 1.5.3
ArgoCD provider version: 5.6
ArgoCD version:2.7.7
```

### Affected Resource
- argocd_cluster

### Debug Output
```
   project.cluster-dev-project (cluster-dev-project): Drift detected (update)
   ╷
   │ Error: failed to read cluster https://random-ip/cluster-dev
   │
   │   with cluster.project-dev-cluster (project-dev-cluster),
   │   on cdk.tf.json line 249, in resource.argocd_cluster.project-dev-cluster (project-dev-cluster):
   │  249:       },
   │
   │ rpc error: code = PermissionDenied desc = permission denied
```

### Steps to Reproduce
1. Have previously created a cluster with terraform
2. Remove cluster manually in argocd
3. Try to refresh state, apply or destroy just the cluster resource

### Expected Behavior
Refresh state and remove cluster from the state when refreshing state

### Actual Behavior
PermissionDenied error, new behaviour of ArgoCD when there is not such resource in the server

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by paco-sisutech** [comment]
Seems like I kind of fix it, just removed the state in terraform for the resource and then run apply, that made it:
terraform state rm cluster.project-dev-cluster

**Comment by w4rgrum** [comment]
@paco-sisutech this is probably linked to this issue: https://github.com/oboukili/terraform-provider-argocd/issues/266
