### ISSUE TITLE
The use_local_config is not effect on 6.0.0

### ISSUE THREAD

**Issue by tan-nguyen-tpv-mti** [oboukili/terraform-provider-argocd#320]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version

```
Terraform version: v1.2.4
ArgoCD provider version: 6.0.0
ArgoCD version: v2.5.3+0c7de21
```

### Affected Resource(s)
- all resource if using `use_local_config = true` in provider

### Terraform Configuration Files
```hcl
provider "argocd" {
  use_local_config = true
}
```
### Panic Output
```
Error: invalid provider configuration: one of `core,port_forward,port_forward_with_namespace,use_local_config,server_addr` must be specified
```

### Steps to Reproduce
1. setup terraform provider as below
```hcl
provider "argocd" {
  use_local_config = true
}
```
2. `terraform apply`

### Expected Behavior
The client connect successfully

### Actual Behavior
Terraform case with message 
```
Error: invalid provider configuration: one of `core,port_forward,port_forward_with_namespace,use_local_config,server_addr` must be specified
```
### Possible issue

![2023-07-27 23_30_38-● model_provider go - terraform-provider-argocd-master - Visual Studio Code](https://github.com/oboukili/terraform-provider-argocd/assets/113092633/8c22970c-4005-4bb7-800b-c20db118d5ef)

**Comment by onematchfox** [comment]
Hi @tan-nguyen-tpv-mti,

My bad! Thanks so much for reporting this and for pointing me in the right direction for the fix, which was a great help! Hopefully, the latest release resolves the issue. If not, feel free to reach out again.
