### ISSUE TITLE
kubeconfig parameter for kubernetes block

### ISSUE THREAD

**Issue by charlysotelo** [oboukili/terraform-provider-argocd#324]
### Description

Add a kubeconfig parameter for the kubernetes block. Currently you may set this via the KUBECONFIG env var, but this will not work when using multiple argocd providers necessitating distinct kubeconfig files

**Comment by onematchfox** [comment]
Hi @charlysotelo,

I'm afraid this is not possible at present as the `argocd` codebase does not provide a mechanism for this to be [configured when using port forwarding](https://github.com/argoproj/argo-cd/blob/21c71320bca7c0b3989e8cb3be28ebe47c75908b/util/kube/portforwarder.go#L21-L106) (relying instead on the standard behaviour of [`NewDefaultClientConfigLoadingRules`](https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/staging/src/k8s.io/client-go/tools/clientcmd/loader.go#L160-L180) in the `kubernetes` module).

That being said... This is pushing my knowledge of k8s configuration, but... I do believe that you can configure multiple `kubeconfig` files in the `KUBECONFIG` environment variable (see [Kubernetes docs](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/)). So, AFAIK, you should be able to configure the env var with all required `kubeconfig` files and then use the provider configuration `kubernetes.config_context` configuration option to specify which context to use from the merged config.

**Comment by onematchfox** [comment]
Stale
