### ISSUE TITLE
Can't alias argocd provider instances

### ISSUE THREAD

**Issue by yuriy-yarosh** [oboukili/terraform-provider-argocd#328]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version
```
Terraform version: 1.5.5
ArgoCD provider version: 6.0.2
ArgoCD version: 2.8.1
```

### Affected Resource(s)
Provider itself when aliased and passed to other resources.

### Terraform Configuration Files
```hcl
provider "argocd" {
  alias = "local"

  username    = "admin"
  password    = local.argocd_password
  port_forward_with_namespace = "argocd"

  kubernetes {
    host = local.bootstrap.endpoint
    cluster_ca_certificate = local.bootstrap.cluster_ca_certificate
    client_certificate = local.bootstrap.client_certificate
    client_key = local.bootstrap.client_key
  }
}

```

### Debug Output

```
argocd_project.this: Refreshing state... [id=cloudreef]
argocd_application.bootstrap_argocd: Refreshing state... [id=proj-argocd:argocd]
╷
│ Error: invalid provider configuration: one of `core,port_forward,port_forward_with_namespace,use_local_config,server_addr` must be specified
│
│
╵
╷
│ Error: invalid provider configuration: one of `core,port_forward,port_forward_with_namespace,use_local_config,server_addr` must be specified
│
│   with argocd_project.this,
│   on project.tf line 1, in resource "argocd_project" "this":
│    1: resource "argocd_project" "this" {
│
```

### Steps to Reproduce

1. Set a provider alias
2. Watch a validation error

### Expected Behavior
Being able to use multiple instances of argocd provider.

### Actual Behavior
Validation fails.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by onematchfox** [comment]
Hi @yuriy-yarosh,

Can you supply a minimal reproducible example of this issue? I have tried but am unable to reproduce this myself. The error, however, indicates a misconfiguration of the provider. This leads me to wonder if you have another non-aliased provider declaration?

**Comment by oboukili** [comment]
I second that, please share your `argocd_project.this` resource declaration. It most likely does not include the `provider` [attribute](https://developer.hashicorp.com/terraform/language/providers/configuration#selecting-alternate-provider-configurations).
