### ISSUE TITLE
Add support for pathParamPrefix in argocd_application_set 

### ISSUE THREAD

**Issue by drdkmkkr** [oboukili/terraform-provider-argocd#329]
### Description

Add support for `pathParamPrefix` in git generators for ApplicationSet.

See: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/#example-two-git-generators-using-pathparamprefix

> If both child generators are Git generators, one or both of them must use the pathParamPrefix option to avoid conflicts when merging the child generators’ items.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by onematchfox** [comment]
Introduced in ArgoCD 2.6, which since the release of ArgoCD 2.8 is the minimum supported version of this provider so no need feature flag.
