### ISSUE TITLE
Helm application not automatically synced when created

### ISSUE THREAD

**Issue by NigelVanHattum** [oboukili/terraform-provider-argocd#343]
When I create an ArgoCD application based on a HELM chart, the application gets created in the correct ArgoCD project as expected. The only problem is, that my application does not automatically gets deployed to my cluster. I can't seem to find any of the information on how to change this behaviour. My project has an always active sync window. 

### Terraform Version, ArgoCD Provider Version and ArgoCD Version

```
Terraform version: v1.6.2
ArgoCD provider version: v6.0.3
ArgoCD version: v2.8.4+c279299
```

## Terraform configuration
```hcl
resource "kubernetes_namespace" "nfs_csi_driver" {
  metadata {
    name   = "nfs-csi-driver"
    labels = {
      "pod-security.kubernetes.io/audit"   = "privileged"
      "pod-security.kubernetes.io/enforce" = "privileged"
      "pod-security.kubernetes.io/warn"    = "privileged"
    }
  }
}

resource "argocd_repository" "nfs_csi_driver" {
  repo = "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts"
  name = "csi-driver-nfs"
  type = "helm"
}

resource "argocd_application" "nfs_csi_driver" {
  metadata {
    name = kubernetes_namespace.nfs_csi_driver.metadata.0.name
  }

  spec {
    project = "system"
    source {
      repo_url        = argocd_repository.nfs_csi_driver.repo
      chart           = argocd_repository.nfs_csi_driver.name
      target_revision = var.nfs_csi_driver_version
    }

    destination {
      namespace = kubernetes_namespace.nfs_csi_driver.metadata.0.name
      name = "in-cluster"
    }
  }
}
```

## Question

How can I make sure that my Helm ArgoCD application also automatically deploys?

**Comment by onematchfox** [comment]
Hi @NigelVanHattum,

Does your application sync/get deployed when you do so manually via the UI? If so then you may want to read up on [Automated Sync Policy](https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/), or take a look at [`sync_policy` in the `argocd_application` resource](https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/application#nested-schema-for-specsync_policy).

**Comment by NigelVanHattum** [comment]
Hi @onematchfox ,

I've looked at those. From the UI it automatically works. I've tried running it before, I might have messed up my indentation. It works with the sync_policy.
