### ISSUE TITLE
When will the next release be? 

### ISSUE THREAD

**Issue by chap-dr** [oboukili/terraform-provider-argocd#366]
Hello. 😄 

With respect, why are no new releases being made to this? We've been waiting for quite a while on this https://github.com/oboukili/terraform-provider-argocd/commit/d84d09101f8c1954cf613df69890a846540692b7 to reach the provider. 

Thank you for this wonderful provider.

**Comment by dtrouillet** [comment]
Hello,

I have the same question for [1f84b3c](https://github.com/oboukili/terraform-provider-argocd/commit/1f84b3ca179dff6cc949cbf6cf17e2d946c7b68c) .

**Comment by oboukili** [comment]
I'll find some time to review the current PRs and make a new release before next week.

At this point I think it's safe to say no current project maintainers have any availability currently (@onematchfox has been working single-handedly for the past year or two past years (already?), and I've watched from the sidelines every now and then).
I think it may be time to donate this project to the CNCF, and/or to find new maintainers. WDYT @onematchfox ?

**Comment by onematchfox** [comment]
Apologies for the delay folks. Unblocking the release pipeline after upgrading `argo-cd` dependencies caused a few issues (one even self-induced :facepalm:) that none of the maintainers had time to deal with. But finally everything is working again and [`v6.1.0`](https://github.com/oboukili/terraform-provider-argocd/releases/tag/v6.1.0) is out the door. Have at it :shipit:
