### ISSUE TITLE
Does the module support the changes on ArgoCD 2.94 and above regarding new request headers mandatory field

### ISSUE THREAD

**Issue by flaviomoringa** [oboukili/terraform-provider-argocd#367]
Hi, 

We are using the terraform module against an installed ArgoCD version 2.9.0.

We where told it's going to be upgraded to 2.9.6.

On ArgoCD v2.9.4 there was a [security fix](https://github.com/argoproj/argo-cd/security/advisories/GHSA-92mw-q256-5vwg), that I'm not sure if it can impact the project/cluster creation via terraform.

This makes all calls to the API to have a mandatory field on the request headers, you can check an example here
https://github.com/argoproj/argo-cd/pull/16930/files

I'm just not sure if the terraform module already takes that into consideration.

Should we be worried by this?

Thanks
Flávio Moringa

**Comment by flaviomoringa** [comment]
Replying to myself here:

I was able to test the terraform module with ArgoCD 2.9.6 and all seems to be working.

It would still be nice to get an answer from developers, to make sure I tested all I needed (I tested adding a cluster and creating a project for that cluster).

Cheers

**Comment by onematchfox** [comment]
@flaviomoringa Sorry for the slow response. Yes, everything should work fine. From the provider's point of view this is all handled under the hood by the implementation in the ArgoCD codebase itself.
