### ISSUE TITLE
Terraform plan, refresh and import failed if we have sync policy with empty set {} for applications

### ISSUE THREAD

**Issue by vikaskulwal** [oboukili/terraform-provider-argocd#370]
Hi,

After upgrading to ArgoCD from 2.4.24 to v2.5.22, application creation started failing with ArgoCD provider v4.3.0 with error:
 `rpc error: code = PermissionDenied desc = permission denied
`
even though, it had proper permissions.

I could relate this error with CLI error documented at: https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.4-2.5/#argocd-app-create-for-old-cli-versions-fails-with-api-version-2516

Hence, I tried to upgrade provider to **5.6.0** and **6.0.3**, which also got failed with error `panic: set item just set doesn't exist` (more details below)

### Terraform Version, ArgoCD Provider Version and ArgoCD Version
```
Terraform version: 1.3.7
ArgoCD provider version: 5.6.0 and 6.0.3
ArgoCD version: 2.5.22
```

### Affected Resource(s)
- argocd_application

### Panic Output
panic: set item just set doesn't exist

> Stack trace from the terraform-provider-argocd_v6.0.3 plugin:
panic: set item just set doesn't exist
goroutine 59 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setSet(0xc001a47350, {0xc000532620, 0x7, 0x7}, {0x29ffd20, 0xc001a47578}, 0xc000986b40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:327 +0x959
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc001a47[350](https://code.siemens.com/mindsphere-mainline/aws-kubernetes/edge-accounts/service-helm/-/jobs/167313660#L350), {0xc000532620, 0x7, 0x7}, {0x29ffd20, 0xc001a47578})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:107 +0x14c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc0005e7ec0?, {0xc0005e7ec0?, 0x6, 0x6}, {0x2b943a0, 0xc000c4f050})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:222 +0x312
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc001a47350, {0xc0005e7ec0, 0x6, 0x6}, {0x2b943a0, 0xc000c4f050})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:109 +0x11c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc001a47350, {0xc0016fb270?, 0x5, 0x5}, {0x29ffd20, 0xc001a47590})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:142 +0x52a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc001a47350, {0xc0016fb270, 0x5, 0x5}, {0x29ffd20, 0xc001a47590})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:103 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc000522500?, {0xc000522500?, 0x4, 0x4}, {0x2b943a0, 0xc000c4efc0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:222 +0x312
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc001a47350, {0xc000522500, 0x4, 0x4}, {0x2b943a0, 0xc000c4efc0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:109 +0x11c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc001a47350, {0xc000c4f110?, 0x3, 0x3}, {0x29ffd20, 0xc001a475a8})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:142 +0x52a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc001a47350, {0xc000c4f110, 0x3, 0x3}, {0x29ffd20, 0xc001a475a8})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:103 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc000b97e00?, {0xc000b97e00?, 0x2, 0x2}, {0x2b943a0, 0xc000c4ef30})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:222 +0x312
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc001a47350, {0xc000b97e00, 0x2, 0x2}, {0x2b943a0, 0xc000c4ef30})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:109 +0x11c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc001a47350, {0xc00129a900?, 0x1, 0x1}, {0x29ffd20, 0xc001a47608})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:142 +0x52a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc001a47350, {0xc00129a900, 0x1, 0x1}, {0x29ffd20, 0xc001a47608})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:103 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0xc001a47350, {0xc00129a900, 0x1, 0x1}, {0x29ffd20, 0xc001a47608})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:89 +0x3f9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc000bb9a80, {0x306e4f8, 0x4}, {0x29ffd20, 0xc001a47608})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:227 +0x210
github.com/oboukili/terraform-provider-argocd/argocd.flattenApplication(0xc001780000, 0x36b9500?)
	github.com/oboukili/terraform-provider-argocd/argocd/structure_application.go:536 +0x288
github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDApplicationRead({0x36b9500, 0xc0004a7c20}, 0xc000bb9a80, {0x2e595e0?, 0xc000929900})
	github.com/oboukili/terraform-provider-argocd/argocd/resource_argocd_application.go:229 +0x2a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000aacc40, {0x36b9538, 0xc000dc3f50}, 0xd?, {0x2e595e0, 0xc000929900})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000aacc40, {0x36b9538, 0xc000dc3f50}, 0xc000d680d0, {0x2e595e0, 0xc000929900})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000124000, {0x36b9538?, 0xc000dc39e0?}, 0xc0009c0480)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x36cd190?, 0xc000124000?}}, {0x36b9538?, 0xc000dc39e0?}, 0xc0009c0300?)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server/tf5to6server.go:105 +0x242
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0xc000c2a120, 0xc000c2a180, {0xc000ee44a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000905680, {0x36b9538?, 0xc000dbf860?}, 0xc0004a6f60)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:746 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x2f101a0?, 0xc000905680}, {0x36b9538, 0xc000dbf860}, 0xc00024bf80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:383 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027e3c0, {0x36c7680, 0xc000e24000}, 0xc000d9e[360](https://code.siemens.com/mindsphere-mainline/aws-kubernetes/edge-accounts/service-helm/-/jobs/167313660#L360), 0xc000f92e10, 0x504e170, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc00027e3c0, {0x36c7680, 0xc000e2[400](https://code.siemens.com/mindsphere-mainline/aws-kubernetes/edge-accounts/service-helm/-/jobs/167313660#L400)0}, 0xc000d9e360, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x28a
Error: The terraform-provider-argocd_v6.0.3 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce
Try to add new application and/or terraform refresh/state import/plan

### Expected Behavior
Terraform should be able to create new application.

### Actual Behavior
Terraform should work as expected

### Workaround 
We could figured out that disabling auto sync and patching all applications to get rid of sync policy completely works
```
# Run this command for every application managed with terraform project
kubectl -n argocd patch applications test-app --type json -p='[{"op": "remove", "path": "/spec/syncPolicy"}]'
```

### Important Factoids
NA

### References
NA

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by vikaskulwal** [comment]
Workaround without removing sync policy. Just set prune and self-heal option to some values(true/false)
```sh
kubectl -n argocd patch applications test-app --type merge -p '{"spec": {"syncPolicy": {"automated": {"prune": false, "selfHeal": false}}}}'
```

**Comment by onematchfox** [comment]
> After upgrading to ArgoCD from 2.4.24 to v2.5.22

Apologies for closing this. But we don't have the resources to support older versions of ArgoCD. The provider didn't officially support either of the versions mentioned (as of when the issue was opened). And, since the release of `v6.1.0` the oldest version of ArgoCD that wedo support is `v2.8.x`. If the issue persist with this version then please feel free to open a new issue.
