### ISSUE TITLE
Feature request: Wait for application destruction

### ISSUE THREAD

**Issue by rojopolis** [oboukili/terraform-provider-argocd#38]
Use case:  EKS cluster and ArgoCD applications are created in the same module.
Issue:  When destroying the module the ArgoCD applications are orphaned becuase the EKS cluster is destroyed before ArgoCD can destroy them.
Solution: Add a wait_for_destoy option to relevant resources.

**Comment by oboukili** [comment]
Hello,
do you mean that unrelated ArgoCD applications actually depend on one another? i.e. an argocd application responsible for creating an EKS cluster and other argocd applications responsible for provisionning other Kubernetes ressources within that same EKS cluster?

If so, that can already be solved by using implicit or explicit Terraform resources dependencies (see https://learn.hashicorp.com/tutorials/terraform/dependencies for examples).

The feature can make some sense however, but can definitely be superceded by the above. I will take a look at the feasibility, that will most likely depend on application status codes.

**Comment by rojopolis** [comment]
No.  My use case is a TF module responsible for creating an EKS cluster and installing some infrastructure related helm charts (e.g ingress controllers).

We're using argoCD to achieve this because the helm provider is problematic for us.  This works great.
When we destroy an environment the module deletes the applications they attempt to cascade the deletion to the kubernetes cluster, however quite often by then Terraform has already proceeded to begin tearing down the EKS cluster so the applications are stuck in a deleting state in ArgoCD.

If the provider polled the application object to wait for it's removal before returning to Terraform I believe it would fix this.  The behavior would be similar to deleting resources such as AWS EKS clusters where the provider waits for the resource destruction to complete before removing it from the state.

**Comment by oboukili** [comment]
I see, this even should be the default in a future release. I will take care of adding an optional flag like you suggested to begin with then.

**Comment by rojopolis** [comment]
You may want to consider implementing this as a 'wait' parameter [like in the helm provider](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#wait).

I believe that if this is set the provider waits for the chart to become stable on install and to become deleted on destroy.  I can imagine scenarios where you'd need terraform to wait for ArgoCD to complete some action before proceeding.

**Comment by rojopolis** [comment]
Thanks @oboukili !  This works perfectly.

**Comment by oboukili** [comment]
Great 👍 ! Thanks for the feedback !
