### ISSUE TITLE
Breaking change in minor revision

### ISSUE THREAD

**Issue by rojopolis** [oboukili/terraform-provider-argocd#53]
The `orphaned_resources` parameter in `argocd_project` changed from a map to a block in 0.5.0.  This is a breaking change, so the major version should increment according to [Semantic Versioing](https://semver.org/#semantic-versioning-200).  In our environment we pin to major version (0 in this case) so that we can pick up new features and fixes automatically while insulating ourselves from breaking changes.

Will this project use the minor version to indicate breaking changes?

**Comment by oboukili** [comment]
I thought about that just after releasing it. You are right, I will create a 1.0.0 release that will be identical to 0.5.0 and delete that one.
