### ISSUE TITLE
Add an argocd_repository_certificate resource

### ISSUE THREAD

**Issue by oboukili** [oboukili/terraform-provider-argocd#56]

**Comment by MrLuje** [comment]
I started looking at implementing this resource. I don't have much experience in resource design and Go isn't my main language, so I may need some help.

The thing is this resource/endpoint support 2 kind of certificates : `ssh` & `https` and the api behaves differently depending on `cert_type`. The request for `ssh` & `https` is the same, according to their OpenAPI.

At first, I though doing something like :
```hcl
resource "argocd_certificate" "simple" {
  server_name  = "gitlab.com"
  cert_type    = "ssh"
  cert_subtype = "ecdsa-sha2-nistp256"
  cert_data    = <<EOT
AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
EOT
}
```

For ssh, all fields are mandatory and you get back all fields plus `certInfo` that can be used as an attribute (with the SHA256 of your cert)

request
```json
{
  "items": [
    {
        "serverName": "github.com",
        "certType": "ssh",
        "certSubType": "ssh-rsa",
        "certData": "QUFBQUIzTnphQzF5YzJFQUFBQUJJd0FBQVFFQXE...=="
    }
  ]
}
```

response
```json
{
    "metadata": {},
    "items": [
        {
            "serverName": "github.com",
            "certType": "ssh",
            "certSubType": "ssh-rsa",
            "certData": "QUFBQUIzTnphQzF5YzJFQUFBQUJJd0FBQVFFQXE...==",
+           "certInfo": "nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8"
        }
    ]
}
```

Now for https, `cert_subtype` is optional and you don't get `cert_subtype` & `cert_info` in the response. But you get `cert_subtype` & `cert_info` when doing a GET on the endpoint afterward.

request
```json
{
  "items": [
    {
        "serverName": "github.com",
        "certType": "https",
        "certData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0...=="
    }
  ]
}
```
response
```json
{
    "metadata": {},
    "items": [
        {
            "serverName": "github-pwet.com",
            "certType": "https",
+           "certSubType": "",
            "certData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0...==",
+           "certInfo": ""
        }
    ]
}
```

So either we keep the same model/resource for both, but sometime the field is mandatory and sometime the field is computed. I don't think this can be designed with current SDK, it can't be dynamically mandatory/computed.

Alternatives would be :
- different resource for each (`argocd_certificate_ssh` & `argocd_certificate_https`)
- same resource but a different TypeSet for each so we can manage different requirements and `ssh` & `https` would be mutually exclusive:

```hcl
resource "argocd_certificate" "simple" {
  server_name  = "gitlab.com"

  ssh {
    cert_subtype = "ecdsa-sha2-nistp256"
    cert_data    = <<EOT
    AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
    EOT
    }
  }
```


```hcl
resource "argocd_certificate" "simple" {
  server_name  = "gitlab.com"

  https {
    cert_data    = <<EOT
    AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
    EOT
    }
  }
```
