### ISSUE TITLE
Error on terraform init

### ISSUE THREAD

**Issue by hmalatini** [oboukili/terraform-provider-argocd#63]
Hi! How are you?
Just want to report an error that I have.
### Context

- I am executing `terraform init` in the project for first time (no state files) and got an error. 
- My terraform version is `Terraform v0.14.6`. Also didn't use terraform 12 or 13 before. I started from 14. 
- I have configured my provider file as the documentation said in: [https://registry.terraform.io/providers/oboukili/argocd/latest](https://registry.terraform.io/providers/oboukili/argocd/latest)
- Tried to use differents versions of argocd provider (includes < 1.0.0) and have the same error

### Files
**providers.tf**
```terraform
terraform {
  required_version = ">= 0.13"
  required_providers {
    argocd = {
      source = "oboukili/argocd"
      version = "1.1.3"
    }
  }
}


provider "github" {
  token = var.github_token
  owner = var.github_owner
}

provider "argocd" {
  server_addr = "${var.argocd_host}:${var.argocd_port}"
  username    = var.argocd_user
  password    = var.argocd_pass
}
```
### Execution
**$ terraform init**
```bash
Initializing modules...
- argocd-repo-connection in modules/argocd-repo-connection
- github-repositories in modules/github

Initializing the backend...

Initializing provider plugins...
- Finding oboukili/argocd versions matching "1.1.3"...
- Finding latest version of hashicorp/github...
- Finding latest version of hashicorp/argocd...
- Installing oboukili/argocd v1.1.3...
- Installed oboukili/argocd v1.1.3 (self-signed, key ID 09A6EABF546E8638)
- Installing hashicorp/github v4.4.0...
- Installed hashicorp/github v4.4.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/hashicorp/github:
- For users on Terraform 0.13 or greater, this provider has moved to
integrations/github. Please update your source in required_providers.


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/argocd: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/argocd

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.
```

**Thank you so much!!!!**

**Comment by oboukili** [comment]
Hi, my guess is that you have a misconfigured Terraform module that does not have the `terraform.required_provider` block like you have within your root module. As such, Terraform tries the default `hashicorp` provider namespace instead of `oboukili`.

Let me know if that helps,

**Comment by hmalatini** [comment]
@oboukili yes, you are right!! I also didn't have providers files inside modules. But I can see that it is required for work well. Thank you so much for the help! 😃

**Comment by oboukili** [comment]
Glad I could help :)

**Comment by alex-shef** [comment]
But if we declare a provider in a module, we can't use 'depends_on' for the module.
