### ISSUE TITLE
Issue using private repo and git ssh url as repo_url

### ISSUE THREAD

**Issue by leosayous21** [oboukili/terraform-provider-argocd#73]
Hello,
First of all, thanks you for your provider. It's very useful to connect multiple clusters to argocd directly from terraform.

We use argocd with private repositories but we can't get the resource "argocd_application" to work properly:

```
resource "argocd_application" "argocd-root-app" {
  metadata {
    name      = "root-${var.prefix}"
    namespace = "argocd"
  }
  spec {
    source {
      repo_url        = "git@github.com:padoa/live-apps.git"
```

We have the following error
```
argocd_application.argocd-root-app Creating...

Error: rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: repository not accessible: parse "git@github.com:padoa/live-apps.git": first path segment in URL cannot contain colon

  on root-application.tf line 2, in resource "argocd_application" "argocd-cluster":
   2: resource "argocd_application" "argocd-cluster" {
```

Here is my version of your provider
```
provider "registry.terraform.io/oboukili/argocd" {
  version     = "1.2.0"
  constraints = "1.2.0"
```

and  terraform is in version `v0.14.8` 

For the creds of the repo, we are using the `CREDENTIALS TEMPLATE URL` feature of argocd and it works well 
Did you ever manage to create an application with a private repo ?

Thank you for your help and great work !

Leopold

**Comment by oboukili** [comment]
Hi, thanks it's appreciated ! :)

Yes when I added the argocd_repo_credentials resources, I have created an acceptance test to test private repositories connectivity, you can check the [configuration used ](https://github.com/oboukili/terraform-provider-argocd/blob/master/argocd/resource_argocd_repository_credentials_test.go#L59-L74) for this test. This error actually comes from ArgoCD not the provider (notice the `rpc error` part).

Could you share the full application spec to validate you did not overwrite the repository type to something other than `git` ?

Other than that it seems you've come across a known upstream ArgoCD issue https://github.com/argoproj/argo-cd/issues/3568 , so not directly related to this Terraform provider!

**Comment by benosman** [comment]
I'm running into this issue, the repository is created using this provider and the config looks like this:

```yaml
- sshPrivateKeySecret:
       key: sshPrivateKey
       name: repo-3918055716
   type: git
   url: git@git.domain.com:sites/example.git
```

Curiously it does work fine if I create the app via a manifest or through the gui, but when using this provider I get the InvalidSpecError above.
