### ISSUE TITLE
Create app with manual sync fails

### ISSUE THREAD

**Issue by olegy2008** [oboukili/terraform-provider-argocd#81]
Please consider this example.
After creating a simple resource "argocd_application" with this sync_policy block:
```
sync_policy {
      sync_options = [
        "CreateNamespace=false"
      ]
    }
```
Provider automatically adds these properties in the state even if `automated = {}` string is omitted inside sync_policy {} block:
```
spec.0.sync_policy.0.automated.allow_empty: "false"
spec.0.sync_policy.0.automated.prune: "false"
spec.0.sync_policy.0.automated.self_heal: "false"
```

So currently there is no way to create an application with manual sync using properties inside sync_policy {} but omitting `automated = {}` string. 
However raw yaml files for argo works that way.
Argocd version is v1.8.7

**Comment by MrLuje** [comment]
Fixed in 2.2.8
