### ISSUE TITLE
Mistake in documentation for cluster tls_client_config?

### ISSUE THREAD

**Issue by Matroxt** [oboukili/terraform-provider-argocd#82]
I can't find a trace of `ca_cert_data` in [schema_cluster.go](https://github.com/oboukili/terraform-provider-argocd/blob/master/argocd/schema_cluster.go), but it still referenced in the GKE example in [docs/ressources/cluster.md](https://github.com/oboukili/terraform-provider-argocd/blob/master/docs/resources/cluster.md).

Has it been replaced with `ca_data`? 
Let's update the doc, otherwise, people may get this error like me:
```
An argument named "ca_cert_data" is not expected here.
```

**Comment by Matroxt** [comment]
Nevermind, the doc on Github is fine, it's the doc on [registry.terraform.io](https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/cluster) that isn't updated

**Comment by oboukili** [comment]
Should be solved since the latest release. Thanks for reporting.
