### ISSUE TITLE
Unable to use sensitive values in terraform 0.15 and 1.0

### ISSUE THREAD

**Issue by pfil-waka** [oboukili/terraform-provider-argocd#83]
Attempting to fetch secret through kubernetes provider fails in 0.15+ due to new implementation of sensitive values:

```hcl
provider "argocd" {
  server_addr = "argo.${var.domain}:443"
  username = "admin"
  password = data.kubernetes_secret.argo-cd-password.data
}
```

│ Error: Incorrect attribute value type
│
│   on argocd.tf line 44, in provider "argocd":
│   44:   password = data.kubernetes_secret.argo-cd-password.data
│     ├────────────────
│     │ data.kubernetes_secret.argo-cd-password.data has a sensitive value
│
│ Inappropriate value for attribute "password": string required.

similarly password=nonsensitive(..) returns same error.

**Comment by oboukili** [comment]
Until I find some time to work on this, couldn't you use the [nonsensitive()](https://www.terraform.io/docs/language/functions/nonsensitive.html) terraform function?
```hcl
provider "argocd" {
  server_addr = "argo.${var.domain}:443"
  username    = "admin"
  password    = nonsensitive(data.kubernetes_secret.argo-cd-password.data)
}
```

**Comment by MrLuje** [comment]
`data.kubernetes_secret.argo-cd-password.data` is a [map](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/secret#data)

The correct usage is something like :
```diff
provider "argocd" {
  server_addr = "argo.${var.domain}:443"
  username = "admin"
-  password = data.kubernetes_secret.argo-cd-password.data
+  password = data.kubernetes_secret.argo-cd-password.data.password
}
```

**Comment by onematchfox** [comment]
See comment above
