### ISSUE TITLE
application set

### ISSUE THREAD

**Issue by stempher** [oboukili/terraform-provider-argocd#88]
Hi
Tell me please if you plan to create a resource for the applicationset
https://github.com/argoproj-labs/applicationset/

**Comment by oboukili** [comment]
Apprently, it's handled by another controller (not argocd), that does not even expose an API. It only watches for ApplicationSet custom resources, therefore it is not possible to manage these kind of resources within this provider.

**Comment by yann-soubeyrand** [comment]
Hello,
If I understand the release notes correctly (https://github.com/argoproj/argo-cd/releases/tag/v2.3.0), this should now be feasible.

**Comment by oboukili** [comment]
I didn’t check if an api endpoint was exposed in the 2.3.0 openapi / swagger. Only if it is then yes.

**Comment by yann-soubeyrand** [comment]
Hum, it seems that the ApplicationSet controller hasn’t been merged (yet?) in the Argo CD application controller, the only novelty is that Argo CD now installs the ApplicationSet and notifications controllers by default.

**Comment by oboukili** [comment]
Therefore it’s not possible.

**Comment by tjouno** [comment]
Hello,

I think it's possible now since the ArgoCD 2.5 : [https://github.com/argoproj/argo-cd/issues/7352](https://github.com/argoproj/argo-cd/issues/7352)

Regards,
