### ISSUE TITLE
Checking host when apply

### ISSUE THREAD

**Issue by LevinDmytro2** [oboukili/terraform-provider-argocd#92]
I am deploying EKS cluster + ArgoCD from scratch.
I want all the resources necessary for work to be created in one terraform state.
When I do not have an ArgoCD server and I want to confuse its creation with terraform and then create resources, then I configure the provider for the future ArgoCD server, which will be created by terraform, but the provider is made in such a way that it tries to connect to the server when starting terraform apply
**Provider configuration**
provider "argocd" {
  server_addr = "not-available-server:443"
  username    = "admin"
  password    = "random-password"
  insecure    = true
  grpc_web = true
}
Error:
╷
│ Error: rpc error: code = Unknown desc = Post "https://argocd.domain.com:443/version.VersionService/Version": dial tcp: lookup argocd.domain.com on 192.168.0.1:53: no such host
│ 
│   with provider["registry.terraform.io/oboukili/argocd"],
│   on provider.tf line 15, in provider "argocd":
│   15: provider "argocd" {

When I use for example kubernetes provider with similar situation I don't have this problem:
provider "kubernetes" {
  host                   = aws_eks_cluster.example.endpoint
  cluster_ca_certificate = base64decode(aws_eks_cluster.example.certificate_authority.0.data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    args        = ["eks", "get-token", "--cluster-name", aws_eks_cluster.example.name]
    command     = "aws"
  }
}

First of all resources will be crteated and after that all resources related to kubernetes trying to deploy with provider setting.
Please help with it.

**Comment by oboukili** [comment]
Hi, I believe this will be resolved by #75 , which depends on #62 . I have not found any free time to work on it yet.

**Comment by YermakovvD** [comment]
Hi! We are also faced with this kind of issue, awaiting fixes 👍
