### ISSUE TITLE
Helmfile support

### ISSUE THREAD

**Issue by jakubigla** [oboukili/terraform-provider-argocd#95]
How can I use a helmfile with this provider? 
Many folks has implemented this already, for instance: https://github.com/travisghansen/argo-cd-helmfile

**Comment by oboukili** [comment]
It would be accomplished through the use of a custom plugin, I believe it's out of the scope of the provider as there is no API for that provided by ArgoCD. You have to set that up directly in the argocd configmap https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/.
