### ISSUE TITLE
REGARDING SERVER ADDRESS IN PROVIDER(ARGO-CD)

### ISSUE THREAD

**Issue by Manoj-07** [oboukili/terraform-provider-argocd#98]
I had given my server address(argocd) as argocd-manoj.com it is showing the following error could anyone please help me to sort out the issue.
![Screenshot from 2021-09-11 20-33-33](https://user-images.githubusercontent.com/64740477/132952223-b1d93442-e1d0-40db-aa8b-e78aaff9a801.png)

**Comment by oboukili** [comment]
Hi, you are exposing argocd api without tls, to make it work, set the provider plain_text attribute to true.

I have to warn you though that your setup is highly insecure, you should not be advertising your unsecured endpoint on a public tracker such as github’s.

**Comment by Manoj-07** [comment]
sir I had used plain_text attribute to true bust also getting the same error could you please let me know how to convert https tp tcp

**Comment by oboukili** [comment]
This is out of the scope of support as this is unrelated to the provider. You may try to ask for help on Argoproj’s channels.

**Comment by Manoj-07** [comment]
sir, could you please let me know how to write  server_addr in provider "argocd"
